### ISSUE TITLE
Drop-In UI with 3D secure

### ISSUE THREAD

**Issue by SanalQuiits** [braintree/braintree-ios-drop-in#100]
### General information

* SDK/Library version: 
* Environment: Sandbox
* iOS Version and Device: iOS 10
* Integration type and version: Latest

### Issue description
Drop in was working properly before adding 3d secure. But when I added 3d secure it asks password but it is not re directed to app. It shows "Safari cannot open page because the address is invalid". 

`let request =  BTDropInRequest()
        request.applePayDisabled = false
        request.paypalDisabled = true
        request.threeDSecureVerification = true
        request.amount = "5.00"
        let dropIn = BTDropInController(authorization: clientTokenOrTokenizationKey, request: request)
        { (controller, result, error) in
            if (error != nil) {
                print("ERROR")
            } else if (result?.isCancelled == true) {
                print("CANCELLED")
            } else if let result = result {
                // Use the BTDropInResult properties to update your UI
                 print(result.paymentOptionType)
                 print(result.paymentMethod)
                 print(result.paymentIcon)
                 print(result.paymentDescription)

                print("Nonce : \(String(describing: result.paymentMethod?.nonce))")

                self.sendDetailsToServer(paynetNonce: (result.paymentMethod?.nonce)!)

            }
            controller.dismiss(animated: true, completion: nil)
        }
        self.present(dropIn!, animated: true, completion: nil)`

**Comment by demerino** [comment]
@SanalQuiits I believe you followed the steps for app switching here: https://developers.braintreepayments.com/guides/3d-secure/client-side/ios/v4#setup-for-app-switch

Did you test the URL callback as described here: https://developers.braintreepayments.com/guides/3d-secure/client-side/ios/v4#testing-the-url-type

We've seen issues when a **Bundle ID** begins with non alpha-numeric characters.

**Comment by crookedneighbor** [comment]
@SanalQuiits Since we haven't heard from you, I'm going to close this issue. If you need further assistance, feel free to comment here.
