### ISSUE TITLE
Paypal taking too much time in Drop in

### ISSUE THREAD

**Issue by umair2ooo** [braintree/braintree-ios-drop-in#101]
is there any way to let user stop tapping to anything when user tap on Paypal in Dropin UI?
Because in Dropin UI, Paypal taking too much time before showing browser, and after returning from the Paypal UI.

**Comment by demerino** [comment]
Thanks for the feedback. We'll look into possible solutions on both sides of the browser switching.

**Comment by demerino** [comment]
Is this still an issue?
