### ISSUE TITLE
Display amount and text in BTCardFormViewController

### ISSUE THREAD

**Issue by incipio-srinu** [braintree/braintree-ios-drop-in#104]
General information

SDK/Library version: DropIn UI V6.2.0
Environment: Sandbox
iOS Version and Device: iPhone 7 plus, iOS 11.0
Integration type: CocoaPods
Issue description

In the earlier versions I found a way to display "summary description" and "total amount". But in the latest versions I didn't found any parameters to pass. My requirement is I want to show the Amount and text in the BTCardFormViewController

Earlier version Syntax
BTPaymentRequest *paymentRequest = [[BTPaymentRequest alloc] init];
paymentRequest.summaryTitle = @"Cart Value"
paymentRequest.displayAmount = @"$ 100";

**Comment by demerino** [comment]
The current version of Drop-in is just a "payment picker". We will look into a solution that allows displaying cart items and amounts in the future.

For now, we suggest creating your own view that displays this information including a payment selection button that launches Drop-in from there.

**Comment by incipio-srinu** [comment]
Hmmm thank you for the support
