### ISSUE TITLE
Pressing "Done" on keyboard from Postal Code input when adding a credit card does nothing

### ISSUE THREAD

**Issue by calvinl** [braintree/braintree-ios-drop-in#105]
### General information

* SDK/Library version: 
6.1.0

* Environment: 
Sandbox, Production

* iOS Version and Device: 
iOS 11.4 on all iPhones

* Integration type and version: 

CocoaPods 1.5.0

### Issue description

When adding a new credit card, after filling in all the details and on the Postal Code input, the keyboard switches to a "Done" button. Pressing this button does nothing and the user must hit the Add Card button on the top right of the screen instead. Shouldn't the expected result  be to either dismiss the keyboard or to trigger the Add Card event?

**Comment by demerino** [comment]
@calvinl Thanks for the report. I see what you mean and it is a bit confusing. We'll look into a solution.

**Comment by demerino** [comment]
6.3.0 fixes this.
