### ISSUE TITLE
How to reduce paymentOptionType size in a UIview?

### ISSUE THREAD

**Issue by irtiza49** [braintree/braintree-ios-drop-in#107]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version: 

### Issue description
I have taken a BTUIKPaymentOptionCardView to show the vissa/American express icon but the icon from Braintree is so large. How to reduce it?

**Comment by demerino** [comment]
You should be able to set the constraints yourself on the view (or use Auto Layout constraints for height and width).

Example:
```
    BTUIKPaymentOptionCardView *cardIcon = [BTUIKPaymentOptionCardView new];
    cardIcon.paymentOptionType = BTUIKPaymentOptionTypeVenmo;
    cardIcon.frame = CGRectMake(100, 100, 100, 100);
    [self.view addSubview:cardIcon];
```

Let us know if you're still having issues.
