### ISSUE TITLE
Error when using with Carthage

### ISSUE THREAD

**Issue by atesztoth** [braintree/braintree-ios-drop-in#111]
### General information

* SDK/Library version: 6.3.0
* Environment: macOS 10.13.6
* Integration type and version: Carthage 0.30.1

### Issue description

Building when using Carthage cannot complete.
Some of the log:

The following build commands failed:
	CompileC /Users/attilatoth/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/braintree-ios-drop-in/6.3.0/Build/Intermediates.noindex/ArchiveIntermediates/BraintreeUIKit/IntermediateBuildFilesPath/BraintreeDropIn.build/Release-iphoneos/BraintreeUIKit.build/Objects-normal/armv7/BTUIKVectorArtView.o BraintreeUIKit/Vector\ Art/BTUIKVectorArtView.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

---

/Users/attilatoth/Developer/mcom-auchan/Carthage/Checkouts/braintree-ios-drop-in/BraintreeUIKit/Vector Art/BTUIKVectorArtView.m:2:1: error: use of '@import' when modules are disabled
@import QuartzCore;
^
1 error generated.

Version 6.2 builds fine tho.

Thanks!

**Comment by demerino** [comment]
We'll work on a fix for this - thanks for the report.

**Comment by demerino** [comment]
Pushed a fix to master - can you try again?

**Comment by atesztoth** [comment]
It works now! Thanks! :)

**Comment by atesztoth** [comment]
Can you tell when I can expect a release containing this change?

**Comment by demerino** [comment]
This week! Working on getting a few more fixes in.

**Comment by demerino** [comment]
Fixed in 6.4.0
