### ISSUE TITLE
Postcode field should support alphanumerical input

### ISSUE THREAD

**Issue by Nonepse** [braintree/braintree-ios-drop-in#112]
### General information

* SDK/Library version: 6.3.0
* Environment: Production
* iOS Version and Device: Tested with iOS 11.4, any model
* Integration type and version: CocoaPods 1.5.0

### Issue description

The postcode field only accepts 0-9 characters. According to [the list of postal code notation schemes](https://en.wikipedia.org/wiki/List_of_postal_codes) it is pretty common to have letters in a post code.
For example `SW11 3BZ` in London.

<img width="300" src="https://user-images.githubusercontent.com/5849587/42766018-4272cb8c-8911-11e8-9520-12eac6beb8a9.png">

I think `BTUIKAppearance.m` [l.35](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Helpers/BTUIKAppearance.m#L35) and [l.55](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Helpers/BTUIKAppearance.m#L55) are the culprits.
The keyboardType is set in `BTUIKPostalCodeFormField.m` [l.16](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Components/BTUIKPostalCodeFormField.m#L16). It should be removed so it falls back to the default type `UIKeyboardTypeDefault` which I believe is the most appropriate for postcodes.

The Android SDK doesn't have this issue.

**Comment by demerino** [comment]
Try setting `postalCodeFormFieldKeyboardType` to the desired keyboard:
```
BTUIKAppearance.sharedInstance().postalCodeFormFieldKeyboardType = UIKeyboardTypeDefault
```
