### ISSUE TITLE
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire   Referenced from: /Users/sunil/Library/Developer/CoreSimulator/Devices/DE0206F1-FD44-4D25-BA5A-5FD72BE5E4C6/data/Containers/Bundle/Application/C08F1BD2-9C68-4282-B565-EA1CB0021EBF/karTesting.app/Frameworks/pintFramework.framework/pintFramework   Reason: image not found

### ISSUE THREAD

**Issue by sunil-chayagol** [braintree/braintree-ios-drop-in#115]
i am facing the above issue . i am trying everything to solve it since 2 days with no luck.
i am using xcode 9.4
alamofire is present in my framework through cocopods which i am trying to use in a single application app .

**Comment by gsubu** [comment]
https://stackoverflow.com/questions/46747801/dyld-library-not-loaded-rpath-libswiftavfoundation-dylib-reason-image-not-fo
