### ISSUE TITLE
Not showing PayPal option in UI

### ISSUE THREAD

**Issue by MiteshiOS** [braintree/braintree-ios-drop-in#120]
Drop In UI is only showing card option.
Here is my implementation

    
![0-sa-d7-14f28553b0fe2635a2f3a1939168eb6a](https://user-images.githubusercontent.com/17427703/45672386-9f076680-bb45-11e8-9f30-64387bfafedb.jpg)

     func fetchClientToken() {
           // TODO: Switch this URL to your own authenticated API
          let clientTokenURL = NSURL(string: "https://braintree-sample-merchant.herokuapp.com/client_token")!
          let clientTokenRequest = NSMutableURLRequest(url: clientTokenURL as URL)
          clientTokenRequest.setValue("text/plain", forHTTPHeaderField: "Accept")
          
          URLSession.shared.dataTask(with: clientTokenRequest as URLRequest) { (data, response, error) -> Void in
               // TODO: Handle errors
               let clientToken = String(data: data!, encoding: String.Encoding.utf8)
               
               // As an example, you may wish to present Drop-in at this point.
               // Continue to the next section to learn more...
               
               self.showDropIn(clientTokenOrTokenizationKey: clientToken!)
          }.resume()
     }

    func showDropIn(clientTokenOrTokenizationKey: String) {
          let request =  BTDropInRequest()
          let dropIn = BTDropInController(authorization: clientTokenOrTokenizationKey, request: request)
          { (controller, result, error) in
               if (error != nil) {
                    print("ERROR")
               } else if (result?.isCancelled == true) {
                    print("CANCELLED")
               } else if let result = result {
                    // Use the BTDropInResult properties to update your UI
                    // result.paymentOptionType
                    // result.paymentMethod
                    // result.paymentIcon
                    // result.paymentDescription
               }
               controller.dismiss(animated: true, completion: nil)
          }
          self.present(dropIn!, animated: true, completion: nil)
     }

**Comment by crookedneighbor** [comment]
Do you have PayPal enabled in the Braintree control panel? See https://developers.braintreepayments.com/guides/paypal/testing-go-live/python#get-production-credentials

**Comment by crookedneighbor** [comment]
I just consulted with one of the developers here who specializes in Python, and he pointed out that if an integration is checking the type directly, subclassing the error could break that integration. In that case, it's probably better to hold off on a change like this until we release the next major version.

An alternative solution would be to add a property to the error that exposes the original error.

**Comment by MiteshiOS** [comment]
@crookedneighbor Yes i already enabled PayPal in Braintree. 
![screen shot 2018-09-18 at 8 17 14 pm](https://user-images.githubusercontent.com/17427703/45698734-502df100-bb86-11e8-8565-9c81ca6a465e.png)

I didn't get you second solution can you please be more specific what i needs to do here.

**Comment by crookedneighbor** [comment]
Sorry, i meant to respond to a different issue with that comment. You can safely ignore it! We'll look into your issue soon.

**Comment by MiteshiOS** [comment]
@crookedneighbor Thank you for this. Actually i have one question over here can i do payment by using only merchant id in mobile app ?

**Comment by crookedneighbor** [comment]
In the sample code you provided, I see: 

```
// TODO: Switch this URL to your own authenticated API
let clientTokenURL = NSURL(string: "https://braintree-sample-merchant.herokuapp.com/client_token")!
```

I assume you copied this from the demo app and just haven't filled it in with your own endpoint to get a client token for _your_ merchant account.

For your second question, are you asking how to do an integration without a client token? You can use a tokenization key, see https://developers.braintreepayments.com/guides/authorization/tokenization-key/ios/v4

There don't seem to be any bugs with the SDK here, so I'm going to close this. For additional help with your integration, please contact our support team directly. https://articles.braintreepayments.com/forms/contact
