### ISSUE TITLE
Handle 422 or 400 Error

### ISSUE THREAD

**Issue by jackwebdesksolution** [braintree/braintree-ios-drop-in#122]
Hello BrainTree team,

### General information

* SDK/Library version: 4.7.2
* Environment: Sandbox
* iOS Version and Device: iOS 9.3 + on any iPhone
* Integration type and version: CocoaPods (latest)

### Issue description
I am using drop-in library to inegrate "Paypal Express checkout". When I try to authorize for one time payment, SDK returns "Value is invalid" with error code 2 and error domain "com.braintreepayments.BTHTTPErrorDomain". 

Is there any way that we can find what is the actual error?
[My Code](https://gist.github.com/jackwebdesksolution/f65e92b88af0c5f64e2ffcaf95355b26)

Thanks

**Comment by jackellenberger** [comment]
Hey @jackwebdesksolution, were you able to dig into this issue at all?
