### ISSUE TITLE
Unable to build project using `carthage update --no-build`

### ISSUE THREAD

**Issue by KoCMoHaBTa** [braintree/braintree-ios-drop-in#124]
### General information

* SDK/Library version: 6.5.0
* Environment: ?
* iOS Version and Device: iOS 12 on iPhone XS Simulator
* Integration type and version: Carthage 0.31.1

### Issue description

I'm using Carthage for dependency manager by integrating the project references to my project directly from the Carthage/Checkout folder.
When i setup the dependency - it cannot build successfully and throws errors.

The Carthage command i use is `carthage update --no-build` - this produces the Carthage/Checkouts from where i integrate all dependencies using project references.
I've also tried to open and build the project directly from Xcode - i get the same error.

For more information - look at the images blow.

![cartfile](https://user-images.githubusercontent.com/1181346/47013737-e38c1f00-d150-11e8-82de-ee176804bc21.png)
![cartfile resolved](https://user-images.githubusercontent.com/1181346/47013738-e424b580-d150-11e8-9578-03ca612c5c84.png)
![embedded_binaries](https://user-images.githubusercontent.com/1181346/47013739-e424b580-d150-11e8-97a6-2a78d73204fe.png)
![error_file](https://user-images.githubusercontent.com/1181346/47013740-e424b580-d150-11e8-9990-9431f6d12110.png)
![error](https://user-images.githubusercontent.com/1181346/47013741-e424b580-d150-11e8-8167-f0ccb17af4b1.png)
![folder](https://user-images.githubusercontent.com/1181346/47013742-e4bd4c00-d150-11e8-94c7-a9cfc93c8848.png)
![link_binary_with_libraries](https://user-images.githubusercontent.com/1181346/47013743-e4bd4c00-d150-11e8-8469-5b1fb1d3f07d.png)
![target_dependencies](https://user-images.githubusercontent.com/1181346/47013745-e4bd4c00-d150-11e8-8856-33671db184c9.png)
![braintree_error](https://user-images.githubusercontent.com/1181346/47013837-306ff580-d151-11e8-8907-4f981fd82295.png)

**Comment by billwerges** [comment]
Hi @KoCMoHaBTa, it looks like you're trying to use our Drop-in feature. If you can checkout our documentation for using Carthage, https://developers.braintreepayments.com/start/hello-client/ios/v4#using-carthage, we note that you'll also need to include the `BraintreeCard` and `BraintreePaymentFlow` frameworks. This documentation is slightly out of date (an update is on the way), so you will also need to add the `PayPalOneTouch`, `PayPalDataCollector`, and `PayPalUtils` frameworks.

The full list of required frameworks is as follows:
```
BraintreeDropIn.framework
BraintreeUIKit.framework
BraintreeCard.framework
BraintreeCore.framework
BraintreePaymentFlow.framework
PayPalOneTouch.framework
PayPalDataCollector.framework
PayPalUtils.framework
```

For optional features, such as Venmo and ApplePay, add these frameworks
```
BraintreeApplePay.framework
BraintreeVenmo.framework
```

Thanks for letting us know about your issue, we'll be updating the docs soon. Let us know if you have any other questions.

**Comment by KoCMoHaBTa** [comment]
Hi,

I've tried adding all if the frameworks you've mentioned. The result is again an error. 
I'm attaching a simple project + link to a video of the setup i'm doing.
It looks like the Drop-In project cannot build.

[BraintreeIntegrationTest.zip](https://github.com/braintree/braintree-ios-drop-in/files/2486158/BraintreeIntegrationTest.zip)

https://www.icloud.com/iclouddrive/0SsWCvpJ-zLmJFWHJeNWaVnMA#braintree_integration_fail_1

**Comment by billwerges** [comment]
Hi @KoCMoHaBTa. It appears you're using Carthage to download the Braintree frameworks, and attempting to manually integrate them in your project. The issue you are seeing is due to the `BraintreeDropIn` project being unable to find the headers located in the `Braintree` project. If you would like to continue using manual integration, you will need to update the header search paths for the projects.

Our supported method for adding the `Braintree` frameworks can be found in the `Carthage` documentation: https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

**Comment by KoCMoHaBTa** [comment]
Hi @billwerges. 
Based on your information, I did a little bit more digging.
It turns out that the BraintreeDropIn project does not have the dependency setup to the Braintree project frameworks.
After i added them manually - the project builds successfully.

Do you think this could be resolved in the main repository?
![dependencies_setup](https://user-images.githubusercontent.com/1181346/47323261-ba452480-d663-11e8-87bc-10786618cd81.png)

**Comment by KoCMoHaBTa** [comment]
@billwerges I've created a PR with the changes needed to resolve the issue.
I've verified that the recommended by you Carthage integration is working correctly.
Also i've checked that Cocoapods integration is also working correctly.
Please double check these and and if there is anything in addition that has to be done - let me know

**Comment by KoCMoHaBTa** [comment]
Here is a sample of the integration.
[BraintreeIntegrationTest_PR.zip](https://github.com/braintree/braintree-ios-drop-in/files/2503715/BraintreeIntegrationTest_PR.zip)

**Comment by demerino** [comment]
@KoCMoHaBTa Thanks for taking the time to create this PR. We'll need to test `Cocoapods` as well and ensure that these changes don't impact that integration.
