### ISSUE TITLE
Users of non-Gregorian calendars have incorrect expiration dates

### ISSUE THREAD

**Issue by calvinl** [braintree/braintree-ios-drop-in#127]
### General information

* SDK/Library version: 
6.5.0

* Environment: 
Production & Sandbox

* iOS Version and Device: 
iOS 12 at least

* Integration type and version: 

### Issue description

If a non-Gregorian calendar is being used, such as the Buddhist calendar, we see expiration dates in the Drop UI that are 548 years ahead of the current date. 

[This code is responsible](https://github.com/braintree/braintree-ios-drop-in/blob/3abdc4b70255c4bad2f0b3d829707815d01f3336/BraintreeUIKit/Components/BTUIKExpiryInputView.m#L32-L44) for choosing the current calendar and then fetching the year, then displaying the years + 20 more years for selection in the Drop UI. 

It looks something like this:

![img_4005](https://user-images.githubusercontent.com/490687/48012721-a3391480-e0f0-11e8-815f-59bbf01681b5.png)

The use case is that some users in Thailand are experiencing this issue because they are using the Buddhist calendar. As far as whether this is a bug or not -- I'm assuming most if not all banks are issuing credit cards with expirations dates on the Gregorian calendar, so would it make more sense to have the above referenced code to always use Gregorian rather than `currentCalendar`?

**Comment by hollabaq86** [comment]
Hi @calvinl thanks for bringing this to our attention! We [merged a PR](https://github.com/braintree/braintree-ios-drop-in/pull/129) that fixes this, which will be included in the next release. If you need the fix before then, here's the [commit](https://github.com/braintree/braintree-ios-drop-in/pull/129/commits/1d63df3513b7689307ae41061dfec15b87623e63).

**Comment by calvinl** [comment]
@hollabaq86 Thank you! Looks great.
