### ISSUE TITLE
card.io integration

### ISSUE THREAD

**Issue by steveholt55** [braintree/braintree-ios-drop-in#13]
I'm wondering if there is any specific reason why card.io integration for card scanning doesn't exist in the iOS Drop In UI?  Android has it https://github.com/braintree/braintree-android-drop-in#cardio

**Comment by demerino** [comment]
Thanks for the comment - we're planning to add support soon - but I can't give a specific timeframe. I'll leave this issue open until we add support.

And please send us any other suggestions/issues you run into.

**Comment by jpage4500** [comment]
just wanted to add my vote for this as well!

When I was researching this I found a PalPal library which has scanning built-in but the UI doesn't look quite as good to me: https://github.com/paypal/PayPal-iOS-SDK/

Anyway, I'll check back to see if this gets updated

thanks,
joe

**Comment by demerino** [comment]
@jpage4500 thanks for adding your vote! This feedback helps us prioritize updates and it sounds like `card-io` support is a game changer for you. We'll absolutely work on adding the support. In the meantime, I'd still urge you to implement Drop-in. _When we do add card-io support_, all you'll need to do is add the library to your app.

**Comment by visualjc** [comment]
Vote from me as well.

Having implemented Stripe with Card.io on two iOS apps that deal with payments in venues (think bars/night clubs and live events), I think this would be a really nice feature to have as part of the drop-in.  

Thanks,

Jim

**Comment by demerino** [comment]
Thanks for all of the votes and interest in Drop-in + card.io!

We've gone ahead and put together a quick PR that adds card.io support without making it mandatory: https://github.com/braintree/braintree-ios-drop-in/pull/16

Feel free to test it or add your thoughts to the PR.

**Comment by demerino** [comment]
Added the support in `5.1.0`. Thanks again for all of the feedback - keep it coming.
