### ISSUE TITLE
Same credit card can add multiple time

### ISSUE THREAD

**Issue by LSmint** [braintree/braintree-ios-drop-in#131]
If user add credit card number where previously added, it won't prompt error to stop user continue add it. Luckily, at least the drop in UI has no duplicate credit card number shown.

The problem occur when i try to delete one credit card. I have to perform delete action twice if the same credit card number added two times previously.

**Comment by demerino** [comment]
Thanks for the feedback. This is something we're looking into. One possible workaround is to set `fail_on_duplicate_payment_method` when creating your `client token` so that duplicate cards can't be added: https://developers.braintreepayments.com/reference/request/client-token/generate/#options.fail_on_duplicate_payment_method

**Comment by LSmint** [comment]
@demerino Thanks for your info, the workaround solution stopped duplicate card with following message "Please review your information and try again."

User may not know it is due to duplicate card created in vault with the alert message. Would be better if message can changes to be more meaningful.

**Comment by simeyla** [comment]
@demerino I'm showing a list of radio buttons for a customer's existing card (100% custom UI) - so when they enter a duplicate I want it to select the card they already have. 

So I tried out what you suggested, and when calling `client.tokenize` I got back the error code `HOSTED_FIELDS_TOKENIZATION_FAIL_ON_DUPLICATE` which is great. However what should I do now? 

It didn't actually tell me what the card was a duplicate of so I can't auto-select it for them.

Do you have a suggestion on how this could work - if at all possible. Would I have to not select `vault=true` and just get the nonce back and check on the server side if it's a duplicate?
