### ISSUE TITLE
Get payment method token from BTDropInResult

### ISSUE THREAD

**Issue by delphiy** [braintree/braintree-ios-drop-in#134]
Hi,

How can I get payment method token from BTDropInResult using Objective C

**Comment by crookedneighbor** [comment]
If you pass a `customer_id` when creating your client token, Drop-in will automatically populate with the vaulted payment methods for that customer, but it will do so with a payment method nonce that represents the payment method, not the payment method token itself.

See: https://developers.braintreepayments.com/reference/request/client-token/generate/ruby#customer_id

For further assistance, please contact https://help.braintreepayments.com
