### ISSUE TITLE
Venmo option not shown in Braintree Dropin on iOS

### ISSUE THREAD

**Issue by deekay42** [braintree/braintree-ios-drop-in#135]
### General information

* SDK/Library version: iOSv4
* Environment: sandbox
* iOS Version and Device: iOS 12.1 on iPhone XR Simulator
* Integration type and version: CocoaPods

### Issue description

The braintree dropin ui IOSv4 does not show the venmo payment option even though I followed the configuration docs at https://developers.braintreepayments.com/guides/venmo/client-side/ios/v4. Other payment options are shown and functional. I don't have the venmo app installed on the device, because on android it simply defaults to a webview if the app isn't installed so I assumed iOS would do the same. Now, however, after looking at the code in the repository I see this:

 if (isVenmoAppInstalled || [BTDropInOverrides displayVenmoOption]) {
                [activePaymentOptions addObject:@(BTUIKPaymentOptionTypeVenmo)];
 }
Does the iOS sdk differ from the Android sdk here and require the venmo app to be installed on the device? The docs don't specify this, so I thought I'd ask for help here.

I launch the drop-in ui like this:

BTDropInRequest *request = [[BTDropInRequest alloc] init];
BTDropInController *dropIn = [[BTDropInController alloc] initWithAuthorization:clientTokenOrTokenizationKey request:request handler:^(BTDropInController * _Nonnull controller, BTDropInResult * _Nullable result, NSError * _Nullable error) {

Thanks!

**Comment by crookedneighbor** [comment]
Can you explain what you mean by the Android SDK using a webview if the Venmo app is installed?

According to this snippet, it shouldn't:

https://github.com/braintree/braintree_android/blob/0eb267a56f24dd3875ddf058ae2b90db0e79c91d/Braintree/src/main/java/com/braintreepayments/api/Venmo.java#L127-L129

As far as I know, the Venmo app needs to be installed for either Android or iOS SDKs.

**Comment by deekay42** [comment]
Interesting... let me double check. I was under the impression that it worked on android without the venmo app installed. However, if the intended behavior is to have the app installed then i'll close this issue. I thought it was supposed to work without.

**Comment by crookedneighbor** [comment]
Is there confusing documentation somewhere that suggests that? Can you post a link?

**Comment by deekay42** [comment]
The documentation is unclear about this. There is no explicit mention on whether it does app-switching or runs in a webview, at least as far as I can tell. For example, paypal will run in a webview if the paypal app is not installed. For consistency I assumed venmo would do the same.

**Comment by padmaramuni0605** [comment]
Nothing happens when I click on Venmo option if Venmo isn't installed
