### ISSUE TITLE
Unable to get braintreedropin framework from carthage update 

### ISSUE THREAD

**Issue by sreexamus** [braintree/braintree-ios-drop-in#136]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by crookedneighbor** [comment]
We're unable to reproduce the problem, but I see this similar looking thing on Stackoverflow: https://stackoverflow.com/a/46200268

Would you mind trying that and letting us know if that resolves your issue?

**Comment by sestevens** [comment]
Closing this issue since it has been inactive for several months. Here are our Carthage integration instructions for anyone who lands here in the future: https://developers.braintreepayments.com/start/hello-client/ios/v4#using-carthage.
