### ISSUE TITLE
Venmo option not appearing in Braintree Dropin on iOS

### ISSUE THREAD

**Issue by vnokh** [braintree/braintree-ios-drop-in#139]
### General information

* SDK/Library version: v4
* Environment: Sandbox
* iOS Version and Device: iOS 12.1 on an iPhone 6s
* Integration type and version: CocoaPods

### Issue description

I am trying to integrate braintree drop-in and Paypal, CC, Apple Pay are appearing but Venmo is not appearing, i configured request.VenmoDisabled = false, Linked Venmo sandbox account in braintree sandbox settings, configured whitelisted Venmo url, kindly guide.

**Comment by demerino** [comment]
Is Venmo installed on the device?

**Comment by scannillo** [comment]
Hello @vnokh , was your issue resolved? If so, we will close the issue. If not we will help you figure out the problem!
