### ISSUE TITLE
Drop-In won't let me know if 3DS failed

### ISSUE THREAD

**Issue by mavris** [braintree/braintree-ios-drop-in#141]
### General information

* SDK/Library version: 4.22.0
* Environment: Sandbox
* iOS Version and Device: iOS 12.1.4 iPhone 7
* Integration type and version: 1.5.0

### Issue description
I have added 3DS on my Drop-In controller! Everything seems to work fine except when I try to fail the 3DS. If I put any other code other than `1234` I was expecting the Drop-In controller to notify me somehow that I should not proceed with checkout.

`let request =  BTDropInRequest()
request.amount = "10.00"
request.threeDSecureVerification = true

let dropIn = BTDropInController(authorization: clientTokenOrTokenizationKey, request: request) { (controller, result, error) in
    if (error != nil) {
    //I was expecting something here if 3DS has failed
        Helpers.print("ERROR")
    } else if (result?.isCancelled == true) {
        Helpers.print("CANCELLED")
    } else if let result = result {
        //I always getting result
    }
})`

**Comment by crookedneighbor** [comment]
The message about putting in `1234` is a bit of a misnomer. Not sure why our 3ds partern does that.

To trigger fail cases, you need to use specific test numbers. See https://developers.braintreepayments.com/guides/3d-secure/testing-go-live/#testing

**Comment by crookedneighbor** [comment]
(to my knowledge, there is no specific test card number that triggers a customer putting in their credentials incorrectly. I think liability is just not shifted then)
