### ISSUE TITLE
Is possible to show only the add payment methods function hiding methods list?

### ISSUE THREAD

**Issue by mrigo** [braintree/braintree-ios-drop-in#142]
### General information

* SDK/Library version: Example: 6.5.0
* Environment: Sandbox/Production
* iOS Version and Device: iOS 12.1 on an iPhone X
* Integration type and version: CocoaPods 1.5.3

### Issue description

Hi,
Braintree Drop In let users add methods or choose from existing methods. Great!

The problem is that I'll do all the transactions from server, so the server needs to know which method the user chosen.
If the user add a new method from the Drop In, the server doesn't know anything about it and the same if the user choose from the Drop In an existing method, the server again doesn't know anything about which method the user chosen.

Is it possible to show maybe only the "Add method" section or to have some information about the payment method chosen b the user, so the server can do the transaction?

Thanks!
\m

**Comment by crookedneighbor** [comment]
I'm a little confused. Why does your server need to know whether it was an existing method or a newly added method? In either case, you'd use the payment method nonce for the transaction. Do you have some additional logic before making the transaction?

**Comment by mrigo** [comment]
Hi,
yes you're right, but I've an UI with the list of payment methods.
When the user add a payment method, I've a recap view with the recap of what the user put in the cart and the payment method.
The app needs some data to show the graphic of the payment methods, data given from the server..
But with the drop-in I can't have all the informations I need to show the method..

**Comment by crookedneighbor** [comment]
Can you give me a more complete example of what you're looking for? I still don't think I understand the problem.

What kind of additional info are you looking for here?

**Comment by sestevens** [comment]
Closing this issue since it's been inactive for a couple months.
