### ISSUE TITLE
how do I get whether the card added is Prepaid or Debit

### ISSUE THREAD

**Issue by symadept** [braintree/braintree-ios-drop-in#144]
### General information

* SDK/Library version:  4.19.0
* Environment:  Sandbox/Production
* iOS Version and Device:  iOS/Android
* Integration type and version:  Native SDK CocoaPods 4.19.0

### Issue description

From the BTDropInController for iOS is there a way to know whether the newly entered card is a Prepaid or NOT. All I get from the callback is BTDropInResult. But I found in PODS a field BTCardNonce->BTBinData->prepaid (String). How to get this value in my BTDropInResult?

Thank you very much

**Comment by demerino** [comment]
You need to cast the `paymentMethod` on the `result` as a `BTCardNonce` when appropriate.
```
if ([result.paymentMethod isKindOfClass:[BTCardNonce class]]) {
    BTCardNonce *card = (BTCardNonce *)result.paymentMethod;
    NSString *prepaid = card.binData.prepaid;
    NSLog(@"PREPAID: %@", prepaid);
}
```

Let us know if you need more assistance.
