### ISSUE TITLE
I create the drop-in ,and present it. then only one paypal appears in the view. why?

### ISSUE THREAD

**Issue by maajian** [braintree/braintree-ios-drop-in#146]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by scannillo** [comment]
Hello :)

We will need more context on your current integration to help you out. The best way is to reach out to our support team where they can work through the problems you're having step by step with you.

You can fill out the online form: https://help.braintreepayments.com/
Or you can call: 877.434.2894
