### ISSUE TITLE
How to dismiss drop in ui when click outside.

### ISSUE THREAD

**Issue by lp2008** [braintree/braintree-ios-drop-in#152]
Hello,
I want to dismiss the drop in ui when click outside of the drop in ui.
right now I can only dismiss when cancel button is clicked.

![Simulator Screen Shot - iPhone Xʀ - 2019-06-18 at 18 54 29](https://user-images.githubusercontent.com/6837443/59683987-f03ea680-91fa-11e9-92e2-c14cf459274b.png)

**Comment by cooperbarth** [comment]
I was able to accomplish this by adding a UITapGestureRecognizer to the main view that calls `func dismiss(animated flag: Bool, completion: (() -> Void)? = nil)` on the BTDropInController. 

```
let tapRecognizer = UITapGestureRecognizer(target: self, action: #selector(dismissView))
tapRecognizer.delegate = self
dropIn?.view.addGestureRecognizer(tapRecognizer)

@objc func dismissView() {
  if (dropIn != nil) {
    dropIn?.dismiss(animated: true, completion: nil)
    dropIn = nil
   }
}
```

Does this solution work for you?

**Comment by lp2008** [comment]
@cooperbarth thanks a lot. it's working.
