### ISSUE TITLE
Import Braintree-ios-drop-in inside custom framework

### ISSUE THREAD

**Issue by Carmelo992** [braintree/braintree-ios-drop-in#162]
### General information

* SDK/Library version: 7.2.0
* Environment: 
* iOS Version and Device: All iOS versions and on devices and simulators
* Integration type and version: Carthage 0.33.0

### Issue description

Hi,
I added your framework inside my app and works perfectly. Now I refactored the code and created a framework that includes the core of my app, including the payment flow.

Now, when I launch the app that uses the framework, it fails with this error at runtime :
dyld: Library not loaded: @rpath/CardinalMobile.framework/CardinalMobile
Referenced from: ...../Frameworks/BraintreePaymentFlow.framework/BraintreePaymentFlow
Reason: image not found

Could you help me to understand this problem?

Thanks

**Comment by sestevens** [comment]
Hi @Carmelo992, when you created the framework, did you add the `CardinalMobile.framework` to the new target per [these instructions](https://developers.braintreepayments.com/guides/3d-secure/migration/ios/v4#additional-setup-for-carthage)?

**Comment by Carmelo992** [comment]
Hi, @sestevens 
I have not added this framework.
Now, the app doesn't fail at runtime.

Thanks a lot

**Comment by sestevens** [comment]
@Carmelo992 Great! It sounds like this issue is resolved, so I'm going to close it.
