### ISSUE TITLE
iOS 8+ cannot use braintree-ios-drop-in?

### ISSUE THREAD

**Issue by ShaoSikang** [braintree/braintree-ios-drop-in#17]
My project base on iOS 8.0 , Can I use braintree-ios-drop-in? Or I need to use braintree_ios.
There is another question, My App cannot jump to PayPal App when I install PayPal App.

Can you please help to solve this issue

Thannk in Advance.

**Comment by demerino** [comment]
@ShaoSikang Thanks for submitting your question.

You need to target `9.0+` as stated in the `braintree-ios-drop-in` README:
> The Braintree iOS Drop-In SDK requires Xcode 7+ and a Base SDK of iOS 9+. It permits a Deployment Target of iOS 9.0 or higher.

However, you can still use `braintree_ios`.

If you're using iOS9+ on your testing device (for testing PayPal app switching) then you'll currently be switched to SFSafariViewController as stated in [our docs](https://developers.braintreepayments.com/guides/paypal/overview/ios/v4#how-it-works):
>Devices running iOS 9 will present this page from a SFSafariViewController modally.
