### ISSUE TITLE
Swift Braintree iOS SDK not supporting threeDSecureRequest for DropIn UI request 

### ISSUE THREAD

**Issue by shankararrk** [braintree/braintree-ios-drop-in#173]
https://github.com/braintree/braintree-ios-drop-in/blob/9a3bc43af96463899b4f8381ca14594d3069f985/DropInDemo/Features/Drop%20In/BraintreeDemoDropInViewController.m#L280

**Comment by sestevens** [comment]
Hi @shankararrk, which version of BraintreeDropIn are you using? Support for 3D Secure was added in version 7.3.0, so you will need to use that version to access the `threeDSecureRequest` on `BTDropInRequest`.

**Comment by shankararrk** [comment]
Hi @sestevens ,

I am developing an application on Swift language. by importing pods of braintree.
As per BrainTree Docs [Here](https://developers.braintreepayments.com/guides/3d-secure/migration/ios/v4#add-new-parameters-to-request) I am using following PODS

`pod 'Braintree'
pod 'Braintree/PaymentFlow'`

However when i was using the braintree's SDK to explore/get threeDSecureRequest property/attribute in dropInRequest it was not available.

` let request = BTDropInRequest()
        request.threeDSecureVerification = threeDSecureVerification
        request.amount = String(cart.total.price)
        request.applePayDisabled = applyPayDisabled ? true : !ApplePayService.serviceAvailable
        request.paypalDisabled = paypalDisabled
        request.venmoDisabled = venmoDisabled`
This is my code and i'm trying to set threeDSecureRequest object to BTDropInRequest() 's request.

But there is no 'threeDSecureRequest' param available for 'BTDropInRequest'

The version you are talking about is the version of 
`pod 'Braintree'
pod 'Braintree/PaymentFlow'` ????

or Do we need to add another pod in our project and update it?

Please let me know on the same. 
Thanks in advance. And appreciate your response to this query. Thanks!

**Comment by shankararrk** [comment]
Hi @sesteven,

As you mentioned, I have tried using version 7.3.0 for `BraintreeDropIn` as follows by importing POD's
` pod 'Braintree', '~> 4.26.0'
    pod 'BraintreeDropIn', '~> 7.3.0'
    pod 'Braintree/PaymentFlow'`

And importing  `import BraintreeDropIn` in my class.
Request working perfectly fine now. and I could able to access the threeDSecureRequest property along with the other properties.

` let request = BTDropInRequest()
        request.threeDSecureVerification = true
        request.amount = String(10)
        request.applePayDisabled = false
        request.paypalDisabled = false
        request.venmoDisabled = false
        request.threeDSecureRequest = requestThreeDSecureTwo // ThreeD Secure 2.0 property
`
Thank you for your Kind help.
Cheers!!

Regards 
Shankar A. :)
