### ISSUE TITLE
Disabling PayPal or Credit Card still shows valued options in the "Recent" section

### ISSUE THREAD

**Issue by LaurentShala** [braintree/braintree-ios-drop-in#179]
### General information

* SDK/Library version: BraintreeDropIn (7.3.0)
* Environment: Production & Sandbox
* iOS Version and Device: iOS 12.4 on an iPhone Xs
* Integration type and version: CocoaPods 1.7.0

### Issue description

As a user that has previously vaulted a PayPal payment method,
when I open the Drop-in UI sheet configured with `paypalDisabled` set to `true`,
I am still able to see and select my valued PayPal from the "Recent" payment method section.

As a developer, when I set the `paypalDisabled` on `BTDropInRequest` to `true`, I expected for PayPal options to be disabled throughout. Keeping payment methods in the "Recent" sections even though they are disabled can cause confusion for the developer and the user.

Please note this is not specific to PayPal. When setting `cardDisabled` to `true`, valued credit cards show up on the "Recent" section as well.

### Suggested Solution 

When configuring the `BTDropInRequest` and setting the `paypalDisabled` to `true`, I think the valued PayPal payment methods in the "Recent" section should not appear.

See the image below for an example of a `BTDropInRequest` with `paypalDisabled` set to `true`.

<img width="545" alt="Screen Shot 2019-09-09 at 6 30 46 PM" src="https://user-images.githubusercontent.com/13071936/64571129-dc559d00-d330-11e9-8bfb-74dbc488e2d2.png">

**Comment by hollabaq86** [comment]
:wave: @LaurentShala, thanks for bringing this to our attention. 

This is definitely an improvement we can make, but to avoid a breaking change we'll have to add an additional parameter that sets whether vaulted payment methods that are disabled will be shown to the user.

For the next major version, we can drop the extra parameter and make this the default behavior tied to any of the `Disabled` payment method settings.

**Comment by LaurentShala** [comment]
Hello @hollabaq86,

Thank you for your quick reply! Adding an extra parameter will work great. Please keep me in the loop when the next major version is released.

Thanks again!

**Comment by RocKer004** [comment]
Hi there, any updates about this ?

**Comment by sestevens** [comment]
@RocKer004 This is work we plan to pick up (hopefully soon), but we don't have an exact timeline for it yet. We'll post here when there are updates.

**Comment by RocKer004** [comment]
Hmm.. thanks for your reply, on android it was enough to update to latest version, it means here that's not the case.. well, I'll be waiting for the updates. Thanks

**Comment by sestevens** [comment]
This has been fixed in [v9](https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.0.0). Please see our [Migration Guide](https://github.com/braintree/braintree-ios-drop-in/blob/master/V9_MIGRATION.md) for steps to update.
