### ISSUE TITLE
No Response with Venmo

### ISSUE THREAD

**Issue by m-s-morgan** [braintree/braintree-ios-drop-in#182]
### General information

* SDK/Library version: 7.4.0
* Environment: Sandbox
* iOS Version and Device: iOS 12.4.1 iPhone X
* Integration type and version: Carthage 0.33.0

### Issue description

When I select Venmo as the payment option, the app correctly switches to the Venmo app, correctly authorizes, and then correctly switches back to my app, but then nothing changes on the Dropin UI and neither a response nor an error is received in the dropin handler. I'm honestly not even sure how I can dig into this deeper. If you can point me in the right direction to help you get more information of what may be causing the problem please let me know. Happy to provide whatever might help.

**Comment by hollabaq86** [comment]
👋 @m-s-morgan, thanks for reaching out. To help us troubleshoot your issue, can you confirm that you have [updated](https://developers.braintreepayments.com/guides/venmo/client-side/ios/v4#setup-for-app-switch) your URL schemes and that you've [updated](https://developers.braintreepayments.com/guides/venmo/client-side/ios/v4#update-your-application-delegate) your app delegate with this URL scheme?

If you can share the parts of your code that handles Venmo, we can take a look and provide feedback. If you're not comfortable sharing in public feel free to [contact Braintree Support](https://help.braintreepayments.com/) referencing this issue with your code.

**Comment by m-s-morgan** [comment]
@hollabaq86 thanks for the quick response. I can confirm that the URL schemes are properly updated and seem to work fine. Every other payment type is working correctly including PayPal and the app correctly opens Venmo, authorizes, and then switches back to my app but then nothing changes from there. There isn't a whole lot of code to show since the dropin seems to be doing everything behind the scenes and the handler is never being called since there's no response or update when my app returns (it simply shows the list of options as if I never selected Venmo to begin with). My code for initializing the dropin can be seen below. If there's something additional I need to be doing to handle Venmo correctly, please let me know. Thanks!
```
BTDropInController *dropIn = [[BTDropInController alloc] initWithAuthorization:self.token request:paymentRequest handler:^(BTDropInController * _Nonnull controller, BTDropInResult * _Nullable result, NSError * _Nullable error) {
        if (error != nil) {
            // handle error
        } else if (result.cancelled) {
            // handle cancel
        } else {
            // handle result
        }
    }];
```

**Comment by scannillo** [comment]
Hello. Can you double check you have properly [whitelisted the venmo URL scheme](https://developers.braintreepayments.com/guides/venmo/client-side/ios/v4#set-up-your-ios-client), set up your app for app switch, and updated your [application delegate](https://developers.braintreepayments.com/guides/venmo/client-side/ios/v4#update-your-application-delegate). 

Your code for displaying the drop-in, which you shared above, works fine as you describe.

**Comment by m-s-morgan** [comment]
@scannillo I apologize I was using `sourceApplication` instead of `options` in my AppDelegate (apparent legacy code) and so clearly it was causing an issue. I am now getting the error “Failed to store Venmo Account in vault” for Venmo purchases only. From what I can tell this is an existing customer issue where if the client token is generated with a customerid venmo appears to function fine, whereas when it's a new customer it's unsuccessful. I've seen fixes for this in the venmo driver but is there anyway to get around this using the dropin? Is there something I can do server side to fix this? I'll gladly open a new issue if you'd like since I believe my original question is resolved. Thanks!

**Comment by scannillo** [comment]
Hi again. No problem! I am glad your issue resolved.

For your next question, I am going to direct you to our support team which can be reached here https://help.braintreepayments.com or 877.434.2894. They are the folks that can help you troubleshoot your integration.

**Comment by m-s-morgan** [comment]
@scannillo ok thanks!

**Comment by m-s-morgan** [comment]
@scannillo support's recommendation is to adjust the code below based on whether a customer exists or not, but I don't believe I have access to this in the dropin. Is there any way I'd be able to change this so that it's adjustable with the dropin or would I have to roll my own solution?
```
    // To vault the Venmo account, change this to YES and use a Braintree client token with a customer ID
    [self.venmoDriver authorizeAccountAndVault:NO WithCompletion:^(BTVenmoAccountNonce * _Nullable venmoAccount, NSError * _Nullable error) {
        if (venmoAccount) {
            // You got a Venmo nonce!
            NSLog(@"%@", venmoAccount.nonce);
        }
    }];
```

**Comment by scannillo** [comment]
That is a question the support team can help you with. Continue your conversation with them!

This tab is for issues with our SDK.

**Comment by m-s-morgan** [comment]
@scannillo I'm super sorry to be a pain, but unless I'm mistaken I believe this is an issue with the `braintree-ios-drop-in`. My question is if there is a way to not vault a venmo transaction as it appears to do this by default. There seems to be a dropin property for optionally vaulting or not vaulting cards, but not sure about venmo. Apologies for my persistence, just trying to figure out if the dropin is even still an option for our needs. Thanks!

**Comment by scannillo** [comment]
No worries. Definitely want to make sure you get the answers you need!

> There seems to be a dropin property for optionally vaulting or not vaulting cards, but not sure about venmo.
 
Our drop-in SDK currently does not offer a functionality to vault Venmo payment methods like it does for cards. However, you can handling the vaulting of Venmo payment methods on your server. See [this documentation](https://developers.braintreepayments.com/guides/venmo/server-side/#vaulting-the-venmo-account). 

It is on our roadmap to offer functionality in the SDK to vault Venmo payment methods!

**Comment by m-s-morgan** [comment]
@scannillo yes the issue for me is that the drop-in SDK seems to currently be trying to vault Venmo payments and then errors with "Failed to store Venmo Account in vault." Is there any way for me to access or change the drop-in's venmo driver so that it does NOT try to vault venmo payments?

**Comment by scannillo** [comment]
I updated my above comment to clarify ^ a few things, so re-read that! I had mixed up our SDKs and apologize for any confusion.

Can you trace back where this error comes from? Where in the SDK? Are you passing `NO` to `authorizeAccountAndVault`?

**Comment by m-s-morgan** [comment]
@scannillo I'm using the drop-in SDK, which from what I can tell, does not give me access to the venmo driver for the Venmo button that it shows. If there's a way for me to change the handler in the drop-in please point me in the right direction. I'm never calling `authorizeAccountAndVault:NO` because I'm assuming either the drop-in SDK or the iOS SDK is calling `authorizeAccountAndVault:YES` for me and I'm also assuming this is where the error is stemming from when it can't associate the token with a current customer. Does the drop-in allow for me to change what happens when the Venmo button that it shows is tapped so that I could call `authorizeAccountAndVault:NO` myself?

**Comment by m-s-morgan** [comment]
^ this pretty much evolved into it's own separate issue so I created on for it #184. Really appreciate the help so far @scannillo :)

**Comment by scannillo** [comment]
Hi @m-s-morgan. I want to apologize for the confusion throughout this thread! I re-read through our conversation and see where things got mixed up. Support suggested you . use`authorizeAccountAndVault:NO`. I ran with their suggestion and forgot that this function _is indeed only_ exposed to merchants integrating with our core SDK. You are correct, and I am so sorry for the confusion and discrepancy in responses. 

Will answer your other question in the new issue.

**Comment by m-s-morgan** [comment]
No problem @scannillo! Appreciate the help.
