### ISSUE TITLE
Card.io Integration

### ISSUE THREAD

**Issue by m-s-morgan** [braintree/braintree-ios-drop-in#183]
### General information

* SDK/Library version: 7.4.0
* Environment: Sandbox/Production
* iOS Version and Device: iOS 12.4.1 iPhone X
* Integration type and version: Carthage 0.33.0

### Issue description

Did something break with the Card.io integration? It no longer seems to offer the option to scan a card in iOS. I have the card.io framework included and a CameraUsageDescription is included. Are there additional steps I can take to check what the issue may be? Thanks.

**Comment by scannillo** [comment]
Hello @m-s-morgan. The [CardIO](https://github.com/card-io/card.io-iOS-SDK) repository has been archived and is no longer maintained.

It is on our radar to remove its offering soon from our drop-in SDK in the next major version release.

**Comment by m-s-morgan** [comment]
@scannillo is there any plan to add a different option for CC scanning to the dropin in the future?

**Comment by scannillo** [comment]
Hey @m-s-morgan, it is currently not on our roadmap to support this. If that changes in the near future, I will re-open and notify you in this issue!

**Comment by m-s-morgan** [comment]
@scannillo perfect thanks!
