### ISSUE TITLE
Localization on Payment Screen and Card Entry screen are cutoff or truncated

### ISSUE THREAD

**Issue by martybalabanka** [braintree/braintree-ios-drop-in#19]
The translated strings for the payment sheet and the card entry/add screens are too long for their space and are getting cutoff and/or overlapping. It would be nice if these were exposed to the drop in controller so that we could change the font/sizing to match the application, be able to easily override the strings to our shorter ones, or if they automatically handled resizing to fix these issues.
<img width="518" alt="screen shot 2017-02-13 at 3 26 13 pm" src="https://cloud.githubusercontent.com/assets/9199835/22901869/22f75c08-f201-11e6-926a-330a7a695f1a.png">
<img width="517" alt="screen shot 2017-02-13 at 3 26 24 pm" src="https://cloud.githubusercontent.com/assets/9199835/22901870/22f7bb08-f201-11e6-90c4-d0c35c8fb8b7.png">
<img width="519" alt="screen shot 2017-02-13 at 3 26 37 pm" src="https://cloud.githubusercontent.com/assets/9199835/22901868/22f6ff42-f201-11e6-8806-c69f18170bb4.png">

**Comment by demerino** [comment]
Thanks for the feedback - yeah we need to fix those labels. We'll look into both of your suggestions to see which one makes the most sense. I'll update when we have a fix ready.

**Comment by mauh-akra** [comment]
Any progress on this? It's almost one month now..

**Comment by demerino** [comment]
I'll should have a PR available for review today. I'll update once it is available.

**Comment by demerino** [comment]
Checkout https://github.com/braintree/braintree-ios-drop-in/pull/34 and see if that works for you.

**Comment by mauh-akra** [comment]
Works perfectly, thanks!

**Comment by demerino** [comment]
Fixed in `5.2.0`.
