### ISSUE TITLE
iOS 13 Dismissing 3DS 2.0 check via swipe down does not invoke startPaymentFlow completion handler

### ISSUE THREAD

**Issue by JeevanThandi** [braintree/braintree-ios-drop-in#194]
### General information
* SDK/Library version: Braintree 4.3.0, BraintreeDropInUI 7.4.0
* Environment: Sandbox / Prod
* iOS Version and Device: any iOS 13 device
* Integration type and version: Cocoapods 1.8.5

### Issue description

![Simulator Screen Shot - iPhone 11 - 2019-10-31 at 16 41 53](https://user-images.githubusercontent.com/6736653/67967341-5d2c6900-fbfd-11e9-8c0b-415428cf85d5.png)

When performing a 3DSecure 2 challenge on iOS 13 with the [](https://developers.braintreepayments.com/guides/3d-secure/migration/ios/v4#custom-ui), the presentation style of the window allows the user to swipe down to dismiss the window as well as a 'cancel' navigation bar button. When pressing 'cancel' the completion handler of the paymentFlowDriver is invoked, however when swiping down to dismiss the 3DSecure view controller, the paymentFlowDriver completion handler is not invoked.

Steps to reproduce
1) Create a PaymentFlowDriver instance:

```
        self.paymentFlowDriver = BTPaymentFlowDriver(apiClient: someBTAPIClient)
        self.paymentFlowDriver?.viewControllerPresentingDelegate = self
```

2) Call 'startPaymentFlowDriver'

```
 self.paymentFlowDriver?.startPaymentFlow(request) { [weak self] (result, error) in
            print("PAYMENT DRIVER FINISHED!!!") //not called when swiping down to dismiss
            if error?._code == BTPaymentFlowDriverErrorType.canceled.rawValue {
                // expected on swiping down 3d 2 view controller, but happens when pressing 'cancel'
                return
            }            
}
```
Observe startPaymentFlow completion handler is invoked when pressing 'cancel' but not invoked when swiping down to dismiss.

Issue Impact: No completion handling on 3D secure check leaves our users stuck in a loading state

Going down this flow,

```
    func paymentDriver(_ driver: Any, requestsPresentationOf viewController: UIViewController) {
```
is not called, so I cannot set a full screen presentation style on the view.

**Comment by demerino** [comment]
Thanks for raising this issue, we'll be looking into it and possible solutions. An update will be posted with our findings.

**Comment by JeevanThandi** [comment]
Hey @demerino - any update on this? :)

**Comment by JeevanThandi** [comment]
@scannillo @demerino my product owner needs an update.... Any progress at all? :)

if this were a bigger issue it would have a response from the wider community as well? The fact it hasn't makes me think I've done something wrong on my side? Would really appreciate if someone could take a look as then we could clear our sprint board 😉

**Comment by demerino** [comment]
@JeevanThandi Can you try updating the Braintree pod (`pod update Braintree`) to version **4.30.2** and test again? I'm unable to reproduce the issue with the latest version.

**Comment by JeevanThandi** [comment]
Forgot to comment on this! Can confirm this is fixed, thank you 👍
