### ISSUE TITLE
Deprecated API usage

### ISSUE THREAD

**Issue by WojciechTrzasko** [braintree/braintree-ios-drop-in#197]
### General information

* SDK/Library version:  7.4.0
* Environment: Sandbox/Production
* iOS Version and Device: iOS 11 and above
* Integration type and version: CocoaPods 1.7.4

### Issue description

Hi,

First of all, I really love your product!

Because of `UIApplication` API deprecations introduced with iOS 13, we investigated our project and its dependencies and find out that Braintree DropIn uses two deprecated properties:
* [statusBarOrientation](https://developer.apple.com/documentation/uikit/uiapplication/1623026-statusbarorientation) - used in `BTUIKExpiryInputView` and in `BTDropInController`.
* [statusBarFrame](https://developer.apple.com/documentation/uikit/uiapplication/1622937-statusbarframe) - used in `BTDropInController`.

Because we are getting close to the release of our project, we would like to be sure that there won't be any surprise at the end. In such a case I would like to ask, do you plan to resolve those in the near future?

Best regards!

**Comment by scannillo** [comment]
Hi @WojciechTrzasko. Thank you for bringing this to our attention. We don't have an ETA on when we can make these updates, but we welcome public PRs if you need these changes urgently!

Team SDK - @hollabaq86

**Comment by WojciechTrzasko** [comment]
Hi @scannillo,
As we have almost the same conversation in the issue for another repository, this time I will try to short the message ;).

We are preparing our app for MVP release in the middle of December and this is a very crucial date for us. Do you think that you will be able to resolve this before that date?

**Comment by scannillo** [comment]
This is not on our current roadmap, but we've added it to our backlog. I do not think we will have this prioritized by then, since it is not blocking your or other's development. If it is however, please let us know.

**Comment by scannillo** [comment]
This was fixed in [v8.1.0](https://github.com/braintree/braintree-ios-drop-in/releases/tag/8.1.0)

**Comment by Crylion** [comment]
@scannillo I just found this old issue, because I was googling the exact same issue, I just encountered it in `BTUIKViewUtil.m` 🤔 

<img width="1274" alt="Screenshot 2023-05-09 at 15 42 46" src="https://github.com/braintree/braintree-ios-drop-in/assets/776753/a508e3a5-907c-44a0-a119-64b471976f37">

**Comment by Crylion** [comment]
@scannillo Thanks for your response 🙏
It's obviously not your job to debug my Xcode woes, and you are absolutely right: you use the `@available` check exactly like the apple documentation suggests it.
And still, I get these errors 😢 
I tried using Xcode 14.2 and 14.3, I'm using 9.8.2 of the BraintreeDropIn pod, and all the "Treat Warnings as Errors" settings are set to "no"... Xcode is really driving me nuts sometimes...
And for the record, I'm doing this in a Capacitor 5 project with a deployment target of 13.0

**Comment by Crylion** [comment]
Update: Finally found the flag I need to set.
In the Pods project, `Deprecated Functions` under Warnings needed to be set to `no`
<img width="463" alt="Screenshot 2023-05-10 at 09 53 39" src="https://github.com/braintree/braintree-ios-drop-in/assets/776753/cfc8cacc-b44f-41c7-9edf-2504595ac8b4">

Sorry to bother you 😅

**Comment by BunnyBuddy** [comment]
We are experiencing same issue with the flutter_braintree package on Mac OS Sonoma. The thing is, if we set this flag and run it in Xcode, everything works well. However, running it from Android Studio (as a normal Flutter app) results in the same error because the flag is reset. 
Can someone enlighten me how we can avoid having this flag reset, or if there is a method to assure it from the iOS/podfile? According to my understanding, this problem occurs when we execute the app in Android Studio since the pod install is run as a pre-command, which may reset the flag to its default behaviour.
