### ISSUE TITLE
After converting the code to Swift 3.0, viewcontroller does not conform to protocol BTViewControllerPresentingDelegate

### ISSUE THREAD

**Issue by intellignt-idiot** [braintree/braintree-ios-drop-in#2]
Hi, after converting my project to the latest Swift 3.0 version , I get this error, even after implementing the delegates.
Please check the attached images :

![screen shot 2016-10-01 at 7 56 42 pm](https://cloud.githubusercontent.com/assets/18556497/19014681/61c51f4c-8811-11e6-9053-15002f0ae38c.png)
![screen shot 2016-10-01 at 7 57 35 pm](https://cloud.githubusercontent.com/assets/18556497/19014683/6da953f0-8811-11e6-8e73-76ed877f732f.png)

And here is what I am using in my pod file :

pod 'Braintree'
pod 'Braintree/DataCollector'
pod 'Braintree/PayPalDataCollector'

**Comment by bluk** [comment]
Hello, the `AnyObject` parameter types should be `Any`. The Swift 3 migrator doesn't seem to handle this 100% correctly. Something similar to the following should compile:

```
    // MARK: - BTViewControllerPresentingDelegate

    func paymentDriver(_ driver: Any, requestsDismissalOf viewController: UIViewController) {
        dismiss(animated: true, completion: nil)
    }

    func paymentDriver(_ driver: Any, requestsPresentationOf viewController: UIViewController) {
        present(viewController, animated: true, completion: nil)
    }

    // MARK: - BTAppSwitchDelegate

    func appSwitcherWillPerformAppSwitch(_ appSwitcher: Any) {
    }

    func appSwitcher(_ appSwitcher: Any, didPerformSwitchTo target: BTAppSwitchTarget) {
    }

    func appSwitcherWillProcessPaymentInfo(_ appSwitcher: Any) {
    }
```

**Comment by intellignt-idiot** [comment]
Thank you very much. It solved the problem.
