### ISSUE TITLE
Drop-In Static Library missing

### ISSUE THREAD

**Issue by kierobinson1** [braintree/braintree-ios-drop-in#20]
Hello,
When adding the Braintree-Drop-In project following the [Braintree Drop in Static Integration Guide](https://github.com/braintree/braintree-ios-drop-in/blob/master/Docs/Braintree-Static-Integration-Guide.md), the library mentioned in step 5 (BraintreeDropIn-StaticLibrary) doesn't seem to exist in the downloaded files. The subproject does have a folder titled "BraintreeDropInStaticLibrary", but it appears to be empty.

Any ideas?

**Comment by demerino** [comment]
@kierobinson1 thanks for bringing this to our attention. You're correct that we have not included a static library. We should not have included those docs, we'll fix that soon. Have you considered Carthage or Cocoapods instead?

**Comment by demerino** [comment]
See https://github.com/braintree/braintree-ios-drop-in/pull/35

**Comment by demerino** [comment]
Fixed in `5.2.0`.
