### ISSUE TITLE
Colors, general styling not appearing correctly

### ISSUE THREAD

**Issue by cjcolej** [braintree/braintree-ios-drop-in#200]
### General information

* SDK/Library version: 7.5.0
* Environment: Sandbox
* iOS Version and Device: iOS 13.2.3 Light Mode & Dark
* Integration type and version: Cocoapods 1.8.3

### Issue description

I've attached screenshots of the issue. The system font is not appearing correctly.

![IMG_0079](https://user-images.githubusercontent.com/25731969/69590719-3d425800-0fa5-11ea-879e-29989f19020e.jpg)
![IMG_0080](https://user-images.githubusercontent.com/25731969/69590727-429fa280-0fa5-11ea-8dca-abf5e2743d5b.PNG)
![IMG_0081](https://user-images.githubusercontent.com/25731969/69590730-46cbc000-0fa5-11ea-926e-9a603eaf3e97.PNG)

**Comment by scannillo** [comment]
Hi @cjcolej. Are you _sure_ you're on version 7.5.0? I ran our Drop-In demo app on an iPhone 11 running iOS 13.2.3 and don't see the same inconsistencies with colors and fonts you are seeing.

**Comment by cjcolej** [comment]
My apologies. I assumed I was on 7.5.0 because I didn't specify a version in my Podfile. I had my deployment target set to 9.0 so it was using an older version of Braintree Core and therefore Drop In
