### ISSUE TITLE
Valid decimal total not processed

### ISSUE THREAD

**Issue by mavris** [braintree/braintree-ios-drop-in#210]
### General information

* SDK/Library version: 4.31.0
* Environment: Both
* iOS Version and Device: iOS 13.2.2
* Integration type and version:  CocoaPods

### Issue description
```
  let request =  BTDropInRequest()
   request.threeDSecureVerification = true     
   let threeDRequest = BTThreeDSecureRequest()
   let total = NSNumber(floatLiteral: 345.6)
   threeDRequest.amount = NSDecimalNumber(value: total.floatValue)
```
This code result to error: "Amount must be a valid number. Allowed characters are numbers and . as an optional decimal point"

**Comment by scannillo** [comment]
Hi @mavris. It looks like you're setting the `amount` as a float. You should only be sending in two decimal places. We replicated the problem you're running into below by using `.floatValue`.

![Screen Shot 2020-01-27 at 10 33 19 AM](https://user-images.githubusercontent.com/35243507/73193645-896a5f80-40f0-11ea-8234-e933866293c5.png)
