### ISSUE TITLE
Braintree iOS drop-in is not showing language according to app. I added SDK by cocoa pods. Please tell me that what i have to do?

### ISSUE THREAD

**Issue by upendralmeter** [braintree/braintree-ios-drop-in#211]
### General information

* SDK/Library version: 
* Environment: 
* iOS Version and Device: 
* Integration type and version:

**Comment by hollabaq86** [comment]
👋 @upendralmeter, what version of the SDK are you using?

It would also be helpful to know how you are testing and on what version of iOS you are testing on.

**Comment by upendralmeter** [comment]
Braintree- iOS v4 SDK
Testing on iPhone XR and also in simulator iPhone Pro, iPhone 8
iPhone XR iOS version is 13.1.2 and Simulator version is 13.3
![arabic](https://user-images.githubusercontent.com/51788731/73868678-f2bd4180-4859-11ea-9580-a699ec6d91b7.jpeg)

**Comment by scannillo** [comment]
May I ask what language you are using in this screenshot? 

Our drop-in SDK will support [these](https://github.com/braintree/braintree-ios-drop-in/tree/master/BraintreeUIKit/Localization) languages.

**Comment by upendralmeter** [comment]
Yes i am using arabic but its showing English only its changing alignment.

**Comment by upendralmeter** [comment]
What happen?

**Comment by scannillo** [comment]
Hi @upendralmeter. Can you send us a screenshot of the iPhone Language you have set on your iOS simulator? You can [set the language](https://www.wikihow.com/Change-the-Language-on-an-iPhone) in the Language & Region section in the settings app. 

Also, is your app a native iOS app?

We cannot replicate your issue currently. When we change our iOS simulator to Arabic, the translations are working fine.

**Comment by upendralmeter** [comment]
Sorry for late reply.

Its working with device language but its not working with app language. So how will it work with app language.

**Comment by sestevens** [comment]
@upendralmeter Could you explain what you mean by "device language" vs. "app language"? Changing the device's language should automatically change the language shown in Drop-in, assuming it's a language for which we provide translations.

Here are a couple screenshots of what we're seeing in our demo app. It would help if you could send us a screenshot of **how you're changing the language in settings.** That way, we might be able to help troubleshoot.

Settings:
![device-settings](https://user-images.githubusercontent.com/51723734/74161727-0b748100-4be5-11ea-9b95-d26ff739911f.png)

Braintree Drop-in:
![braintree-drop-in](https://user-images.githubusercontent.com/51723734/74161440-8ee1a280-4be4-11ea-9cca-1e8ec9a3a709.png)

**Comment by upendralmeter** [comment]
Yes i got your point and also already told you that its working with device arabic language. Let me explain-

My application is supporting two language one is English and another one is Arabic. And its independent from device language. Means without changing device language we can change our application language using localisation feature of application.

So when i am changing my app language using localisation then its not changing drop-in language but its changing alignment from left to right.

Are you getting my points? I am adding two screen shots. 

I took this screenshot when device language is Arabic- 
![IMG_1607](https://user-images.githubusercontent.com/51788731/74266377-4544a500-4d15-11ea-9281-e7346d43ebfc.PNG)

I took this screenshot when device language is English but our app language is Arabic through localisation feature. In this case only changing the alignment not changing the text. 
![IMG_1608](https://user-images.githubusercontent.com/51788731/74266400-4c6bb300-4d15-11ea-9b0b-6fc6a64a5334.PNG)

**Comment by scannillo** [comment]
Hello @upendralmeter. So, I think when you specify "app language" vs "device language" you are referring to this new feature of iOS 13 (https://www.howtogeek.com/441716/how-to-change-the-language-of-an-app-on-your-iphone-or-ipad/). Using the instructions in that article, I tried to replicate your issue using two scenarios

1. Device language in English with app language in Arabic
2. Device language in Arabic and app language in English

In both situations, the drop-in looks appropriate for each language. I am unable to replicate your issue.

Potentially you are referring to a custom "app language" that you are setting manually in your app somewhere? We will need more specifics on how to replicate this.

**Comment by upendralmeter** [comment]
Okay thanks for your support and let me know one more thing-

Can we change the text of this pop-up(Wants the use Paypal.com to sign in ) or can we remove this pop-up ?

![Simulator Screen Shot - iPhone 11 Pro - 2020-02-12 at 19 26 16](https://user-images.githubusercontent.com/51788731/74355683-3b32ad00-4dce-11ea-8b98-3b8ca11e9e9d.png)

**Comment by scannillo** [comment]
This pop-up cannot be modified and is required that the customer give consent to share information to complete the Pay with PayPal flow.

Do you have any other information regarding your original issue? If not, I will close this GitHub issue.

**Comment by upendralmeter** [comment]
Okay Thanks
