### ISSUE TITLE
Application stuck upon tapping PayPal option from popup

### ISSUE THREAD

**Issue by dimitrismakrisgr** [braintree/braintree-ios-drop-in#217]
### General information

* SDK/Library version: Latest
* Environment: Sandbox
* iOS Version and Device: iOS 13.3.1

### Issue description

I have integrated Braintree SDK correctly, and I have specified the url type to Info.plist.

Then I initialise the BTDropInController via:

`let request = BTDropInRequest()`
`request.applePayDisabled = true`
`request.cardDisabled     = true`
`request.venmoDisabled    = true`

`let dropIn = BTDropInController(authorization: tokenString, request: request) { [weak self] 
    (controller, result, error) in
}`

`guard let paypalController = dropIn else {
            return
        }`

`present(paypalController, animated: true, completion: nil)`

The popup is showing correctly, but upon tapping the PayPal option from popup, the application is stuck.

Could you please provide feedback why this happens as well as any other info I can provide to solve this?

Attached also the state of the main thread.

![Screen Shot 2020-03-10 at 5 56 20 PM](https://user-images.githubusercontent.com/14997227/76334710-20cfee80-62fc-11ea-8510-5545a4e7a7a8.png)

Thanks in advance!

**Comment by billwerges** [comment]
Hi @dimitrismakrisgr,

It's a little unclear on what you mean by "stuck". Are you experiencing a crash within your application, or just not seeing any UI activity?

**Comment by dimitrismakrisgr** [comment]
No, the application does not immediately crashes. It freezes, nothing is clickable and no UI is presented, and after some time the OS kills it.

**Comment by scannillo** [comment]
Hi @dimitrismakrisgr - I suggest you instead reach out to Braintree Support at https://help.braintreepayments.com, where they can help you troubleshoot your integration.
