### ISSUE TITLE
Enable setting the text color for the NavigationBar and content separately

### ISSUE THREAD

**Issue by balazsgerlei** [braintree/braintree-ios-drop-in#22]
If I understood properly, the text color of the NavigationBar and the content (TextFields) can only be set to the same color (with the `primaryTextColor` property). It would be nice to be able to set these separately because than a dark background color for the NavigationBar and a light background color for the rest of the screen (or the other way around) can be used. I think many apps use this kind of contrast in their UI.

I hope you will add a possibility for this, thank you!

**Comment by demerino** [comment]
@balazsgerlei Thanks for the feedback! We can look into adding a new property that lets you specify the navigation bar *title* color. We will need to ensure it doesn't break existing integrations that use the `primaryTextColor`.

**Comment by balazsgerlei** [comment]
Thank you, I am looking forward to this.

**Comment by demerino** [comment]
Added this feature to #34

**Comment by demerino** [comment]
Fixed in `5.2.0`.
