### ISSUE TITLE
BTThreeDSecureRequestDelegate onLookupComplete method not calling for 3DSecure v2

### ISSUE THREAD

**Issue by frankemmanuvel** [braintree/braintree-ios-drop-in#221]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 8.1.0
 - Environment: Sandbox
 - iOS Version: 13.0
 - Device iPhone 11
 - Integration type & version Carthage 0.34.0

**Describe the bug**
Implemented BTThreeDSecureRequestDelegate and the delegate method onLookupComplete. This method only calls if the 3DSecure version is .version1. If the version set to .version2, this delegate method won't call. 

**To Reproduce**
1. Go to add payment method.
2. Click on add Credit or Debit Card
3. Add Card details.
4. Click on Add Card
3. See error (Delegate method is not calling)

**Expected behavior**
It should call the "onLookupComplete" method before the 3d secure.

**Comment by scannillo** [comment]
When integrating with 3DS while using the Drop In, follow [these docs](https://developers.braintreepayments.com/guides/3d-secure/client-side/ios/v4#drop-in-ui). You only need to conform to `BTThreeDSecureRequestDelegate` and `onLookupComplete` for the custom UI setup when using Braintree iOS.
