### ISSUE TITLE
Provide a way to skip the "Select Payment Method" modal if only one kind of payment available

### ISSUE THREAD

**Issue by balazsgerlei** [braintree/braintree-ios-drop-in#23]
If I am correct, there is currently no way with the newest version of the dop-in UI to skip the "Select Payment Method" modal view, even if only one method is supported by the app. It means an additional and quite unnecessary step for the user and has no advantages so it would be nice if there is a way to skip it entirely (when there are no more payment method to choose from).

**Comment by demerino** [comment]
@balazsgerlei Do you mean automatically showing the PayPal or Credit Card forms after launching Drop-in if that is the only possible choice?

**Comment by balazsgerlei** [comment]
Yeah, exactly!

**Comment by demerino** [comment]
We will consider this for future **major** UI revisions. Closing for now.
