### ISSUE TITLE
Mastercard logo contains white fill background

### ISSUE THREAD

**Issue by joeboyscout04** [braintree/braintree-ios-drop-in#230]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 8.1.1
 - Environment: Sandbox
 - iOS Version: iOS 13
 - Device iPhone 11 
 - Integration type & version: Cocoapods

**Describe the bug**
We are looking at displaying some of the payment options using `+ (BTUIKVectorArtView *)vectorArtViewForPaymentOptionType:(BTUIKPaymentOptionType)type;`  

Doing some testing, we noticed that the Mastercard brand logo has a white background, which doesn't match the other icons, which don't have a solid background.
I realize that the logo may be an issue in dark mode, which is possibly why it would have this white background (to enforce contrast with the black "mastercard" text.  However, I think this would probably be solvable by either removing the "mastercard" text from the logo, or by changing the text color depending on the `BTUIKAppearance.colorScheme`

**To Reproduce**
1. Load image ` BTUIKViewUtil.vectorArtView(for: .mastercard)`

**Expected behavior**
I would expect the logo to not have a white background.

**Screenshots**

![BraintreeLogos](https://user-images.githubusercontent.com/1489809/90284419-46948d00-de72-11ea-930b-bd6eda835a09.png)

**Comment by sestevens** [comment]
Hey @joeboyscout04 👋  Sorry for the slow response on this. Just wanted to let you know that we'll look into this issue just as soon as we have the bandwidth. Thank you for reporting it!

**Comment by scannillo** [comment]
Hi @joeboyscout04. Hello! We are soon releasing v9 of the Braintree Drop-in SDK, which will have `BTUIKViewUtil` no longer be public. Unfortunately, accessing these vectors individually is not an intended feature of the Drop-in.

To access an icon image for a payment method, use `BTDropInResult.paymentIcon`.

If you need logos for specific payment methods or card types, we recommend getting them from the brand's site directly.
