### ISSUE TITLE
Apple Pay should not be hidden when the device supports Apple Pay

### ISSUE THREAD

**Issue by ejensen** [braintree/braintree-ios-drop-in#232]
**Integration Details:**
 - SDK/Library Version: Braintree drop-in 8.1.1
 - Environment: All
 - iOS Version: All
 - Device All
 - Integration type & version: All

**Describe the bug**
The Braintree drop-in UI currently hides the option for Apple Pay when the device does not yet have a payment method in its wallet. This prevents users from knowing that Apple Pay is available, and they can add a payment method to use it. Hiding the Apple Pay button on devices that support it goes against [Apple's Human Interface Guidelines for Apple Pay](https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/offering-apple-pay/):

> Offer Apple Pay on all devices that support it. If the device doesn’t support Apple Pay, don’t present Apple Pay as a payment option. On all capable devices, show the Apple Pay button.
> When users choose an Apple Pay button to make a purchase, but their device doesn’t have Apple Pay set up, they’re given the opportunity to set up Apple Pay. Don’t disable or hide an Apple Pay button.

The drop-in UI is using the following code to determine if the Apple Pay button should display:
```swift
- (BOOL)canMakeApplePayPayments {
    return [PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.applePaySupportedNetworks];
}
```
The code returns `NO` when there is not yet a payment method setup in Wallet. 

**To Reproduce**
1. Present the Braintree drop-in UI on a device capable of Apple Pay, but does not yet have a payment method in Wallet.
2. Notice that Apple Pay is not an option in the Braintree drop-in UI

**Expected behavior**
Following [Apple's Human Interface Guidelines for Apple Pay](https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/offering-apple-pay/):
The Apple Pay button is available in the Braintree drop-in UI.
When selected, Apple's `PKPaymentAuthorizationController` guides the user through the process of adding a payment method to their wallet.

**Comment by scannillo** [comment]
Hi @ejensen - thank you for bringing this concern to us. I have added it to our teams list of to-dos and we will update you.

**Comment by sestevens** [comment]
This has been fixed in [v9](https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.0.0). Please take a look at our [Migration Guide](https://github.com/braintree/braintree-ios-drop-in/blob/master/V9_MIGRATION.md) for steps to update.
