### ISSUE TITLE
App Store Connect release not possible 

### ISSUE THREAD

**Issue by stoppi** [braintree/braintree-ios-drop-in#239]
I am using the latest version of braintree-ios-drop-in (8.1.1) in my Xamarin app. Everything works fine, but Apple is rejecting my app bundle for the following reason:

"ITMS-90338: Non-public API usage - The app references non-public selectors in App: setErrorDetail:, setTransactionID:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/"

Prior versions are working and I can upload them to the app store as well.
I searched for the mentioned symbols (setErrorDetails and setTransactionID) both are contained in CardinalMobile.framework.

**Comment by scannillo** [comment]
Hi @stoppi - thanks for bringing this issue to our attention.

Can you try specifying the latest version of `Braintree` in your Podfile? 

```
pod 'Braintree', '~> 4.35.0'
```

We updated our version of the CardinalMobile dependency in [v4.35.0](https://github.com/braintree/braintree_ios/blob/master/CHANGELOG.md#4350-2020-08-10) and first want to rule out that this isn't doesn't fix your issue.

**Comment by stoppi** [comment]
Hi @scannillo, 

I am using Braintree version 4.35.0, this includes CardinalMobile version 2.2.3.

**Comment by scannillo** [comment]
Ok - thanks for checking.

> Prior versions are working and I can upload them to the app store as well.

Can you specify which versions of Braintree were working for you?

**Comment by scannillo** [comment]
I've created a sample app with TestFlight and am not able to trigger the same App Store Connect rejection issue. I wonder if  either TestFlight isn't able to catch warnings at the same level as the real App Store, or if using Xamarin is part of the issue.

**Comment by stoppi** [comment]
Hi @scannillo,

The last version working for me was version 4.11.0.
Since I use the Xamarin wrapper https://github.com/NAXAM/braintree-ios-binding this was the last available version.

Would it be possible to send me your working IPA, so that I can compare?

**Comment by scannillo** [comment]
Sure - here is my sample app that includes `BraintreeDropIn` and `Braintree` v4.32.0.

[iOS14_braintree4_32_0.zip](https://github.com/braintree/braintree-ios-drop-in/files/5402561/iOS14_braintree4_32_0.zip)

**Comment by scannillo** [comment]
Sure - here is a sample app including `BraintreeDropIn` and `Braintree` v4.35.0
[14testApp.zip](https://github.com/braintree/braintree-ios-drop-in/files/5402588/14testApp.zip)

**Comment by scannillo** [comment]
I am able to confirm that `setTransactionId` matches a grep for CardinalMobile in Braintree v4.35.0 and does not in Braintree v4.11.0. I see no matches for `setErrorDetail` in either.

**Comment by stoppi** [comment]
I can confirm, `setErrorDetails `comes from another third party (Naxam CardinalMobile wrapper for Xamarin).
And since you can publish your app including CardinalMobile with `setTransactionId`, that should not be the problem.

**Comment by scannillo** [comment]
Ok - I will close this issue for now then. Feel free to re-open if you're able to trace the issue back to our SDK.
