### ISSUE TITLE
Cordova implementation it is posible?

### ISSUE THREAD

**Issue by patrykKlimczak** [braintree/braintree-ios-drop-in#242]
Is your feature request related to a problem? Please describe.
Create app of native framework7 (vue) with dropin braintree Javascript, but apple store not allow to push app with only card payments so I need apple pay subscription in my cordova app.

Describe the solution you'd like
I need use subscription payment base on braintree with apple pay options on app cordova (framework7)

Do you have maybe any solutions?

**Comment by sestevens** [comment]
I'm going to close this issue since it was addressed in the Braintree iOS repo ([#551](https://github.com/braintree/braintree_ios/issues/551)). Let us know if you need any additional help, or feel free to reach out to [Braintree Support](https://help.braintreepayments.com/)!
