### ISSUE TITLE
threeDSecureVerification authentication page won't return to app

### ISSUE THREAD

**Issue by aa599** [braintree/braintree-ios-drop-in#254]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 8.1.2
 - Environment: Production
 - iOS Version: 14.3 (and others)
 - Device: iPhone SE 2 (and others)
 - Integration type & version:  CocoaPods 1.8.4

**Describe the bug**
When using threeDSecureVerification, successful authentication doesn't return to app in production.
It works in sandbox.

**To Reproduce**
1. Cause Drop-in to open
2. Click on credit card
3. Goes to "Authentication Successful", then opens a browser page on assets.braintreegateweay.com with button "RETURN TO APP". Never auto redirects back to app, tapping the button has no effect.
4. With threeDSecureVerification disabled, app works.

**Expected behavior**
tapping 'RETURN TO APP' should return to app

I saw a similar report (RETURN TO APP not working) on android in 2018.

**Comment by hollabaq86** [comment]
👋 @aa599 thanks for reaching out. Can you [contact Support](https://help.braintreepayments.com/) with the following info to help our investigation?

- your production merchant ID
- does this issue happen only on devices using iOS 14.3? Or does it happen on other iOS versions?
- does this issue happen only with a specific card number or for all 3DS verification attempts?
