### ISSUE TITLE
After showing a 3DS v2 flow, review request alert is not visible

### ISSUE THREAD

**Issue by Mirconet** [braintree/braintree-ios-drop-in#257]
**Integration Details:**
 - SDK/Library Version: Braintree 4.3.6.1, BraintreeDropInUI 8.1.1
 - Environment: Sandbox / Prod 
 - iOS Version: 14.3
 - Device: any iOS 14.3 device
 - Integration type & version: Cocoapods 1.9.1

**Describe the bug**
After performing a 3DSecure version 2 challenge on iOS 14.3, if we try to show a system review request (SKStoreReviewController) the alert appears behind our current key window and is not visible to the user. The same when using the 3DSecure challenge version 1 works correctly. Using dispatchAsync / dispatchAfter doesn't help in this case.

**To Reproduce**

Create a PaymentFlowDriver instance:
```
        let paymentFlowDriver = BTPaymentFlowDriver(apiClient: apiClient)
        paymentFlowDriver.viewControllerPresentingDelegate = braintreePresentingDelegate
```

Call 'startPaymentFlowDriver'
```
        paymentFlowDriver.startPaymentFlow(threeDSecureRequest) { result, error in  
            SKStoreReviewController.requestReview()
            // Other code
        }
```

**Screenshots**

<img width="267" alt="Prima_Staging_on_iPhone_8__iOS_14_3_" src="https://user-images.githubusercontent.com/6652514/104444052-8aadca00-5597-11eb-8564-5f967db8ed34.png">

**Comment by scannillo** [comment]
👋  Hello @Mirconet. Thanks for using Braintree! A few things:

1) So for an iOS Braintree Drop-In integration with 3DS, you don't need to call `startPaymentFlow`. Please check our [our docs here](https://developers.braintreepayments.com/guides/3d-secure/client-side/ios/v4#using-3ds). You need to set the `DropInRequest.threeDSecureVerification` bool and `DropInRequest.threeDSecureRequest` object.

2) According to Apple's docs, there is no guarantee that the rating alert view will be presented when `SKStoreReviewController.requestReview()` is called. Here is the snippet from[ Apple's docs](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview):
    > Although you should call this method when it makes sense in the user experience flow of your app, the actual display of a rating/review request view is governed by App Store policy. Because this method may or may not present an alert, it's not appropriate to call it in response to a button tap or other user action.

    I don't think this is an issue with our 3DS UI, but instead with how Apple is deciding when to show that alert. I would experiment with moving the `SKStoreReviewController.requestReview()` call outside the completion of `startPaymentFlow` (potentially near where you submit your nonce for transaction to your server). Best of luck!

**Comment by Mirconet** [comment]
Hi @scannillo, 
1. I'm not using the drop-in at this moment, but I choose to open the issue here because I have seen others on 3DS check opened here and not strictly related to drop-in like this https://github.com/braintree/braintree-ios-drop-in/issues/194

2. I know about the app rating alert Apple policy, but I even know that in debug the alert is always shown to help developers. In fact if you look at the screenshot the rating alert is shown, but behind the current viewController.

3. As I wrote in fact the alert is shown correctly if I use the 3DS version 1, but after using the 3DS version 2 there is no way to show the rating alert, even changing position to `SKStoreReviewController.requestReview()` or after some other viewController transition.

**Comment by cbarbera80** [comment]
Same here but with another kind of alert popup. It seems like a window issue. Maybe the 3ds ui presentation broke something in window?
