### ISSUE TITLE
Detect when 'Add Card' view controller opens so that status bar color can be changed

### ISSUE THREAD

**Issue by meismyles** [braintree/braintree-ios-drop-in#27]
_**Moved from [braintree_ios issue tracker](https://github.com/braintree/braintree_ios/issues/316).**_

Currently, when the 'Add Card' view controller is presented when using the drop-in UI, there seems to be no way to detect that this has shown, and this means that if using the default light theme, if using a white status bar style, it cannot be seen since it blends in with the nav bar.

I know you also offer a dark theme but it seems like there should either be a way of being notified that the 'Add Card' flow has opened so we can change the status bar style ourselves manually, or in the drop-in framework, maybe in the BTUIKAppearance customisation options, an option should be given to set the status bar style.

**Comment by demerino** [comment]
We'll look into the different options here to see what works best. Do you have a preference?

**Comment by meismyles** [comment]
Personally, I would say the most preferable option is to have the Drop-in handle this itself. You take away work from the developer then. So:
1. Store the current status bar style just before the 'Add Card' view is opened.
2. Depending on the Drop-in theme chosen, apply either the black status bar if light theme chosen, or white status bar if dark theme chosen.
3. Set the status bar style back to stored value on close.

**Comment by demerino** [comment]
See #36 

I do think that Drop-in should do the work. To simplify things, I've created a PR that simply hides the status bar for "full screen" views. Let me know what you think.

**Comment by demerino** [comment]
Fixed in `5.2.0`.
