### ISSUE TITLE
Localization not working for Carthage integration

### ISSUE THREAD

**Issue by mbuchetics** [braintree/braintree-ios-drop-in#272]
**Integration Details:**
 - SDK/Library Version: 8.1.2
 - Environment: Sandbox & Production
 - iOS Version: -
 - Device -
 - Integration type & version: Carthage

**Describe the bug**
I integrated the Drop-In framework using Carthage but all strings appear in English, even though the device & app is set to another supported language (e.g. German).
It works fine when integrating using Cocoapods.

**Expected behavior**
The strings to be localized.

**Workaround**
The problem is, that the code uses a `Braintree-UIKit-Localization.bundle` for the localized strings which is not generated using Carthage. Cocoapods generates the bundle, therefore a workaround is to use a Cocoapods projects (e.g. the DropIn Demo) to generate the bundle and then manually copy it over to the Carthage project.

**Comment by sestevens** [comment]
@mbuchetics Thank you for reporting this! I'm able to reproduce the issue on my end, but I'm still working on a fix.

**Comment by scannillo** [comment]
Hello @mbuchetics - a fix for this was released in [v8.1.3](https://github.com/braintree/braintree-ios-drop-in/releases/tag/8.1.3). Thanks for opening this issue!

**Comment by mbuchetics** [comment]
thank you!

**Comment by mbuchetics** [comment]
@scannillo  are you sure this is working? I just got around to updating the frameworks and now I only see the default english strings in the UI.

**Comment by mbuchetics** [comment]
some additional information: I am integrating using XCFrameworks (see https://github.com/braintree/braintree-ios-drop-in/issues/268), maybe this causes the issue. 

workaround: I added the BTUI.string files manually to my project and used `BTUIKLocalizedString.setCustomTranslations(...)` to set the "custom" translations.

looking forward to full SPM support, so I can get rid of all my workarounds :)

**Comment by sestevens** [comment]
@mbuchetics I only tested this with Carthage and CocoaPods, since we don't have official SPM support for Drop-in yet. We're working on adding support at the moment, on a branch called `next-major-version`. I'll definitely test this out on that branch to see if there are any changes we need to make so that localizations work with SPM integrations.

**Comment by sestevens** [comment]
Ah, I looks like I misread your comment as saying that you're already using SPM. I can test this out with Carthage and xcframeworks to see if there's something different we need to do there.

**Comment by sestevens** [comment]
@mbuchetics OK, I gave this a try, and it seems to be working for me. I ran the commands you mentioned in #268:

```
carthage bootstrap --platform ios
carthage update --platform ios --no-use-binaries --use-xcframeworks
``` 

When I run my test app, I see the localized strings:

![Simulator Screen Shot - iPhone 12 - 2021-03-19 at 21 21 17](https://user-images.githubusercontent.com/51723734/111856537-62c14680-88f9-11eb-8b48-3092f2e59399.png)

Here's my test app, if you want to take a look at it: https://github.com/sestevens/CarthageTestApp. Maybe there's something else that you're doing differently?

**Comment by mbuchetics** [comment]
@sestevens  Thank you for the quick response. Your example also works fine for me, so I guess there is something I am doing differently but I haven't figured it out so far. It's no problem right now though, as we needed to add custom translations anyway (Czech) and I will take another look once the SPM integration is done.

**Comment by sestevens** [comment]
Sounds good! 👍

**Comment by sestevens** [comment]
@mbuchetics I have a hunch that the reason this isn't working is because once you specify a custom translation for Czech, the SDK expects all other localized strings to live in the same bundle. We'll have to look into how to support a custom translation for some languages and our built-in translations for other languages.
