### ISSUE TITLE
ETA for braintree_ios 5.0 support

### ISSUE THREAD

**Issue by alexito4** [braintree/braintree-ios-drop-in#278]
If I'm not mistaken the drop-in library still depends on version 4 of the BT SDK. 
Is there any ETA to know when a new version will be released that supports BT SDK 5?
5 fixes an issue that prevents us from compiling the app with some configurations and specially around the M1.

Any information is welcomed, thank you.

**Comment by sestevens** [comment]
@alexito4 We don't have an ETA at this point, but this is something we're actively working on. We're planning to release a new major version of Drop-in that uses version 5 of Braintree iOS, adds support for Swift Package Manager and improves accessibility.

**Comment by alexito4** [comment]
Thank you for the quick reply. That new version seems to include everything we're waiting for ^^ Cheers

**Comment by scannillo** [comment]
@alexito4 I am curious which fix in Braintree iOS v5 regarding the M1 you're referring to?

**Comment by alexito4** [comment]
@scannillo 
> Update Kount SDK to v4.1.3 (includes arm64 simulator architecture for Apple silicon)

We have been having issues with that dependency for months where it doesn't let us compile with some specific configuration. It didn't block us because it works when building for the app store and when running from Xcode. But it was blocking our QA automation since it didn't compile on that specific combination. 
But now that devs are using M1 is even worse because it doesn't let compile at all on the M1 for simulator. We're hoping this is a fix for that.

**Comment by RamblinWreck77** [comment]
+1 on this, we have a new product/app that's prepping for launch that uses 100% SwiftUI/SPM and we'd like to use this updated version with it.

I hope work is going well :)

**Comment by sestevens** [comment]
@RamblinWreck77 You can check out this work on our [`next-major-version`](https://github.com/braintree/braintree-ios-drop-in/tree/next-major-version) branch. We're hoping to do a beta release for it soon.

**Comment by sestevens** [comment]
Hi everyone, we just released a beta version of the Drop-in SDK that uses Braintree iOS v5: https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.0.0-beta1.

We recommend taking a look at our [Migration Guide](https://github.com/braintree/braintree-ios-drop-in/blob/master/V9_MIGRATION.md) if you want to check out this beta.

**Comment by sestevens** [comment]
We just released v9 of the Drop-in SDK, which uses Braintree iOS v5: https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.0.0.

Again, we recommend looking at the [Migration Guide](https://github.com/braintree/braintree-ios-drop-in/blob/master/V9_MIGRATION.md) for help updating.
