### ISSUE TITLE
Add a check to determine whether the customer added a new card or used a recent card

### ISSUE THREAD

**Issue by kierobinson1** [braintree/braintree-ios-drop-in#28]
In the completion of the Drop-in controller it would be nice to know if the customer used a new card or a recent card. Specifically for us, this would be for use in analytics so we can see how many customers are purchasing with recent cards, but I'm sure there are other uses.

Submitting a pull request shortly showing what this change could look like.

**Comment by meismyles** [comment]
See #29.

**Comment by demerino** [comment]
@kierobinson1 This is a great idea - should we consider adding any other events that could be useful for your analytics?

**Comment by kierobinson1** [comment]
@demerino I can't think of any other events we could track at the minute, just this one!

**Comment by demerino** [comment]
Closing in favor of #29
