### ISSUE TITLE
BTDropInController returning BTHTTPErrorDomain code 4 (BTHTTPErrorCodeMissingBaseURL)

### ISSUE THREAD

**Issue by dejanskledar** [braintree/braintree-ios-drop-in#31]
#### Developer Info

- Braintree SDK version: 4.7.5

- Braintree Dropin version: 5.1.0

- Integration type and version: CocoaPods 1.2.0

- Environment: Sandbox

#### Issue Details

When trying to initialize the `BTDropInController` with the token, I get from our server I instantly get an error. The same token is working on Android, though (tested). The Braintree test token works as expected. 
My code:
```
let request = BTDropInRequest()
if let dropIn = BTDropInController(authorization: token, request: request, handler: { (controller, result, error) in
    if (error != nil) {
        // Error
    }
    controller.dismiss(animated: true, completion: nil)
}) {
    viewController.present(dropIn, animated: true, completion: nil)
}
```
The error details:
```
Domain=com.braintreepayments.BTHTTPErrorDomain Code=4 "(null)" UserInfo={path=v1/configuration, method=GET, parameters={
    configVersion = 3;
}}
```
Code 4 means: 
```
/// The BTHTTP instance was missing a base URL
BTHTTPErrorCodeMissingBaseURL,
```

Comparing our token with the test token:
**Our token:**
![image](https://cloud.githubusercontent.com/assets/13760486/24297538/70f4e2ca-10a3-11e7-8f34-4c38e03d5883.png)

**Test token:**
![image](https://cloud.githubusercontent.com/assets/13760486/24297567/859c6464-10a3-11e7-9c70-4b54f7e84553.png)

Looks like our token has a lot less information than the test token from Braintree. I'm not sure why...

When looking at the source of Braintree, I found out that Braintree tries to get the `baseURL` from the decoded token - **BINGO**:
```
NSURL *baseURL = [self.clientToken.json[@"clientApiUrl"] asURL];
```

So the problem is that our token doesn't have the `clientApiUrl`. If I manually insert the `clientApiUrl` into our token, the `BTDropInController` works perfectly. So the working (modified) token looks like this:
![image](https://cloud.githubusercontent.com/assets/13760486/24297676/e84c6046-10a3-11e7-8991-24b0e05eebb3.png)

### The question:
Why do I get such a short token - without the `clientApiUrl`? I don't see any settings regarding this on the Braintree admin panel. Is there any way to set the default baseURL? Why does Android work, but iOS doesn't?

**Comment by demerino** [comment]
@dejanskledar Which server SDK are you using (e.g. Ruby, PHP...)?

**Comment by dejanskledar** [comment]
@demerino It's PHP v3.

**Comment by demerino** [comment]
@dejanskledar  - this looks like a bug in the iOS SDK. You can temporarily specify that you want v2 client tokens in PHP while we work on the fix: https://developers.braintreepayments.com/reference/request/client-token/generate/php#version

**Comment by demerino** [comment]
The fix for this should go out in the next release.
