### ISSUE TITLE
Not compiling in a mix SPM/CocoaPods project

### ISSUE THREAD

**Issue by alexito4** [braintree/braintree-ios-drop-in#325]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 9.0.0
 - Integration type & version: SPM

**Describe the bug**
The BraintreeDropIn package doesn't compile. It uses macros to define how to import some files and it detect the COCOAPODS build setting even if it is integrated with SPM.

**To Reproduce**
1. Have an Xcode project with Cocoapods integrated.
2. Add braintree-ios-drop-in to the project as an SPM package.
3. Doesn't compile. 

**Expected behavior**
The package should compile fine even when the host project uses cocoapods.

**Screenshots**

![Screenshot 2021-04-30 at 09 25 02](https://user-images.githubusercontent.com/750912/116662337-f3c61b80-a995-11eb-8334-e849c1b6ebbf.png)

**Comment by sestevens** [comment]
Hey @alexito4, thanks for opening this issue! We'll get a fix out for this soon.

**Comment by sestevens** [comment]
@alexito4 We released a fix for this today. It's version [9.0.1](https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.0.1). I'm going to close this issue for now, but let us know if you still see any problems!

**Comment by alexito4** [comment]
Seems to be working fine @sestevens 👍🏻  thank you for the quick turnaround.
