### ISSUE TITLE
PayPal Drop-In callback not called if PayPal not set up in-app but enabled in the web portal

### ISSUE THREAD

**Issue by kierobinson1** [braintree/braintree-ios-drop-in#33]
We have implemented the Braintree Drop-In into our app, and noticed that the `BTDropInController`'s callback function isn't called when PayPal isn't set up in-app but is selected as the payment type. The callback could be necessary (and is for us) if we enabled PayPal on our portal for Web transactions but not for our mobile platform. In this case, we want the callback so we can show a pop up saying 'Coming soon'.

**Comment by demerino** [comment]
@kierobinson1 One solution is to not include the PayPal SDK if you haven't `set it up` yet. Would that be possible?

**Comment by kierobinson1** [comment]
@demerino Is there any way to stop the PayPal SDK being installed through the normal `Braintree` and `BraintreeDropIn` pods?

**Comment by demerino** [comment]
Drop-in will [require](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeDropIn.podspec#L30-L32) `Braintree/Core`, `Braintree/Card` and `Braintree/UnionPay`. Then just include the [subspecs](https://github.com/braintree/braintree_ios/blob/master/Braintree.podspec) from Braintree that you `need`.

Example:
```
pod 'BraintreeDropIn'
pod 'Braintree/Apple-Pay'
pod 'Braintree/3D-Secure'
pod 'Braintree/DataCollector'
```

**Comment by demerino** [comment]
Closing, reopen if you need more help.
