### ISSUE TITLE
Plugin uses APIs made unavailable to extensions in iOS 15/Xcode 13b3

### ISSUE THREAD

**Issue by JetForMe** [braintree/braintree-ios-drop-in#343]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 9.1.0
 - iOS Version: Deploy 14.4, 15b3 SDK
 - Integration type & version SPM

**Describe the bug**

Compiling our project, which uses the Braintree drop-in, results in the following errors:

```
…/SourcePackages/checkouts/braintree-ios-drop-in/Sources/BraintreeDropIn/Helpers/BTUIKViewUtil.m:238:27: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

…/SourcePackages/checkouts/braintree-ios-drop-in/Sources/BraintreeDropIn/Helpers/BTUIKViewUtil.m:250:42: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

…/SourcePackages/checkouts/braintree-ios-drop-in/Sources/BraintreeDropIn/Helpers/BTUIKViewUtil.m:263:64: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

…/SourcePackages/checkouts/braintree-ios-drop-in/Sources/BraintreeDropIn/Helpers/BTUIKViewUtil.m:271:46: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

        return CGRectGetHeight(UIApplication.sharedApplication.statusBarFrame);
                                             ^
In module 'UIKit' imported from …/SourcePackages/checkouts/braintree-ios-drop-in/Sources/BraintreeDropIn/Helpers/BTUIKViewUtil.h:1:
≥/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:114:54: note: property 'sharedApplication' is declared unavailable here
@property(class, nonatomic, readonly) UIApplication *sharedApplication NS_EXTENSION_UNAVAILABLE_IOS("Use view controller based solutions where appropriate instead.");
                                                     ^
…/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:114:54: note: 'sharedApplication' has been explicitly marked unavailable here

```

**To Reproduce**
1. Build an iOS app with the drop-in with Xcode 13b3

**Comment by scannillo** [comment]
👋  Hey @JetForMe - we will take a look at this on the new beta. Thanks for opening this issue!

**Comment by JetForMe** [comment]
I'm under a crushing deadline or I would have explored a workaround. I'm still stuck on 13b1, in part because 13b2 changed the way an API works ("cgImageRepresentation() and previewCGImageRepresentation() now return CGImage? instead of Unmanaged<CGImage>? in Swift. (44734827)"), making it incompatible with <=13b1, and in part because I deleted my 13b2, so my only option is 13b3, and I can't move to that because of this issue. I'm not sure what you guys use the shared application for (I mean, I can see the calls you're making, but I don't know their purpose, or if our use of the drop-in even ends up there.

So, I'd really love to be able to move to b3 to see if I can resolve this AVFoundation change in a way that works under both Xcode 12 and 13. Thanks!

**Comment by scannillo** [comment]
👋  Looks like this issue is related to a bug fix in the latest Xcode beta:
[See release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes)
> Linking Swift packages from application extension targets or watchOS applications no longer emits unresolvable warnings about linking to libraries not safe for use in application extensions. This means that code referencing APIs annotated as unavailable for use in app extensions must now themselves be annotated as unavailable for use in application extensions, in order to allow that code to be used in both apps and app extensions. (66928265)

[A similar issue in the Facebook SDK was found.](https://github.com/facebook/facebook-ios-sdk/issues/1799)

Will keep you updated as we work on a fix.

**Comment by JetForMe** [comment]
Yeah, I had a related issue in one of my own apps with an update in Xcode 11.4. I look forward to your fixes!

**Comment by scannillo** [comment]
👋  Hi @JetForMe - v9.2.0 has been released with this fix! https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.2.0

Thank you again for reporting this issue to us 😄
