### ISSUE TITLE
Force changing of Drop-In language

### ISSUE THREAD

**Issue by andrii-lisovskiy** [braintree/braintree-ios-drop-in#344]
I am working on iOS app, added BrainTreeDropIn with cocoapods. I need to change language of dropIn as user changes language in app, but currently it works only after app reloaded. Can I force this somehow in runtime?

**Comment by scannillo** [comment]
👋  Hello @andrii-lisovskiy - thanks for opening this feature request.

Our SDK uses [NSLocale's `preferredLanguages`](https://developer.apple.com/documentation/foundation/nslocale/1415614-preferredlanguages) [here](https://github.com/braintree/braintree-ios-drop-in/blob/89960b951004560377aac72bc84f859643cb1b9a/Sources/BraintreeDropIn/Localization/BTDropInLocalization.m#L8-L16). We determine what preferred language the user's device has set, and use that for the DropIn UI. We currently do not have a way to force the Drop In to change its language based on some input. 

I'm a little confused as to your use-case. Is your app trying to set the language preferences for the user's device, or is there just a language option in your app itself? If you could provide some more detail here (ex: APIs used) that would be very helpful!

Also this is a good read - https://developer.apple.com/news/?id=u2cfuj88.

**Comment by scannillo** [comment]
Hi @andrii-lisovskiy - due to lack of activity, I will be closing this issue.
