### ISSUE TITLE
Ios dropIn

### ISSUE THREAD

**Issue by Annafis187** [braintree/braintree-ios-drop-in#346]
https://github.com/braintree/braintree-ios-drop-in/blob/89960b951004560377aac72bc84f859643cb1b9a/Sources/BraintreeDropIn/Public/BraintreeDropIn/BTDropInRequest.h#L26

**Comment by Annafis187** [comment]
> [braintree-ios-drop-in/Sources/BraintreeDropIn/Public/BraintreeDropIn/BTDropInRequest.h](https://github.com/braintree/braintree-ios-drop-in/blob/89960b951004560377aac72bc84f859643cb1b9a/Sources/BraintreeDropIn/Public/BraintreeDropIn/BTDropInRequest.h#L26)
> Line 26 in [89960b9](/braintree/braintree-ios-drop-in/commit/89960b951004560377aac72bc84f859643cb1b9a)
>  @property (nonatomic, strong, nullable) BTPayPalRequest *payPalRequest;

**Comment by scannillo** [comment]
Hi - this Issue template has not been filled in at all. If you want to file an issue, please fill out the template.
