### ISSUE TITLE
Compiling error on simulator

### ISSUE THREAD

**Issue by skywalkerlw** [braintree/braintree-ios-drop-in#351]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 8.2
 - Environment: Sandbox
 - iOS Version: iOS 14
 - Simulator

**Describe the bug**
`
ld: warning: ignoring file /Users/leo/Library/Developer/Xcode/DerivedData/Demo-iOS-boyfuewrajnmygepufldrdsrwdwx/Build/Products/Debug-iphonesimulator/CardinalMobile.framework/CardinalMobile, missing required architecture arm64 in file /Users/leo/Library/Developer/Xcode/DerivedData/Demo-iOS-boyfuewrajnmygepufldrdsrwdwx/Build/Products/Debug-iphonesimulator/CardinalMobile.framework/CardinalMobile (2 slices)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ToolbarCustomization", referenced from:
      objc-class-ref in BraintreeThreeDSecure.o
  "_OBJC_CLASS_$_TextBoxCustomization", referenced from:
      objc-class-ref in BraintreeThreeDSecure.o
  "_OBJC_CLASS_$_CardinalSession", referenced from:
      objc-class-ref in BraintreeThreeDSecure.o
  "_OBJC_CLASS_$_LabelCustomization", referenced from:
      objc-class-ref in BraintreeThreeDSecure.o
  "_OBJC_CLASS_$_UiCustomization", referenced from:
      objc-class-ref in BraintreeThreeDSecure.o
  "_OBJC_CLASS_$_ButtonCustomization", referenced from:
      objc-class-ref in BraintreeThreeDSecure.o
  "_OBJC_CLASS_$_CardinalSessionConfiguration", referenced from:
      objc-class-ref in BraintreeThreeDSecure.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

To be highlighted, it's OK on iPhone device. This problem only exists on simulator.

Is there any workaround on simulator?

**Comment by sarahkoop** [comment]
Hi @skywalkerlw - Thanks for using the Braintree iOS Drop-in SDK. We are aware of this issue on simulators on M1 Macs. Our 3DS provider is still blocking this for us. You can follow that thread here - braintree/braintree_ios#564.
