### ISSUE TITLE
New Release with Apple Silicon Support

### ISSUE THREAD

**Issue by aChase55** [braintree/braintree-ios-drop-in#359]
Braintree Package requirement is bumped to 5.5.0 on master branch, however, a new release hasn't been cut since this change has been made. Please release a new version with updated Package.swift

**Comment by scannillo** [comment]
Hi. Thanks for opening this issue. We made this release at v9.3.0 of `braintree-ios-drop-in` (https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.3.0).
