### ISSUE TITLE
Card validation for 19 digit VISA and Discover cards

### ISSUE THREAD

**Issue by BalachandranK2** [braintree/braintree-ios-drop-in#360]
Hi Team,
Our requirement is to validate and support 19 digit Discover cards. Currently we are not able to see validation logic for that. In BTUICardType, the defaultMaximumCardLength is 16 and Discover card is initialised with this default length.
Is there a way to validate Discover card with 19 digits with Braintree.

**Comment by scannillo** [comment]
Support for 19 digit Discover cards was released in [v9.1.0](https://github.com/braintree/braintree-ios-drop-in/blob/master/CHANGELOG.md#910-2021-07-01). Please update to that version to get the fix!
