### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by 1280103995** [braintree/braintree-ios-drop-in#361]
Although this is an ```ReactNative``` project, this seems to be a problem with the native code.

I created a v0.66.2 RN project, added ```react-native-braintree-dropin-ui": "^1.1.3"```, and ran ```pod install```, and then ran ```yarn ios```, an error occurred.  

But it runs successfully in xcode.
...................................................................................
<img width="1010" alt="4e3b-781c-4b07-9102-997523b96c89" src="https://user-images.githubusercontent.com/17424486/141096697-6dd27f9c-b8aa-429e-89a6-de93bd6c9e7f.png">

My Xcode version: 12.5
Device: iMac mini 2018
Cocoapods version: 1.11.2

**Comment by scannillo** [comment]
Hi. Our iOS SDK doesn't offer support for yarn, and we don't offer any official React Native support. It looks like you're using `react-native-braintree-dropin-ui` and not `braintree-ios-drop-in` directly. `react-native-braintree-dropin-ui` is not developed or supported by PayPal & Braintree engineers. I encourage you to open an issue with them!

If there is a broader issue regarding our iOS SDK integration that they (or you) can give us details to replicate on, feel free to let us know!
