### ISSUE TITLE
Xcode Cloud --> Failure on "Build for testing"

### ISSUE THREAD

**Issue by dcilia** [braintree/braintree-ios-drop-in#362]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 9.3.0
 - Environment: Production
 - iOS Version: 15
 - Device iPhone 13 Simulator
 - Integration type & version Xcode 13.1, swift package

**Describe the bug**

Hello, we are using a project with Xcode Cloud as our CI, and are currently getting build failures when trying to run unit tests.  Everything works locally.  The error is associated with ```PPRiskMagnes``` no such module --> during a build for testing phase of the workflow.  

**To Reproduce**
Create an app and build with Xcode Cloud, import BTAPIClient in a unit test and try to run the tests with Xcode Cloud.

**Expected behavior**
Compile successfully.

**Screenshots**

<img width="323" alt="braintree" src="https://user-images.githubusercontent.com/992986/142050799-2a96fb6e-5637-4622-932e-7af70c9a8f7d.png">

**Comment by dcilia** [comment]
Resolved this by manually adding the Braintree iOS swift package as well and selecting the appropriate frameworks I needed.  Hope this helps someone else.

**Comment by scannillo** [comment]
👋  Hi @dcilia - thanks for opening this issue! 

This sounds like the same issue outlined here https://github.com/braintree/braintree_ios/issues/735, which is a [known Xcode bug](https://bugs.swift.org/browse/SR-13803).

I am going to close this issue, so we can track the problem in the issue linked above. If anything else, comes up please let us know!
