### ISSUE TITLE
how to fix background color issue in BTCardFormViewController?

### ISSUE THREAD

**Issue by pratik-io** [braintree/braintree-ios-drop-in#363]
I'm using braintree-dropIn SDK: BraintreeDropIn (8.1.4)
After presenting `BTDropInController`, I choose option `Credit or Debit card` from list. And i got this. Transparent navigation bar for `BTCardFormViewController`.

I'm using Xcode Version 13.0 and device iPad Pro(9.7 inch) - iOS 15.0

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-12-04 at 10 59 44](https://user-images.githubusercontent.com/32726267/144699874-63c38ef6-beb3-4750-b498-3f4e413521b4.png)
 
Thank You

**Comment by scannillo** [comment]
This was fixed in v9.3.0!
