### ISSUE TITLE
Xcode can't file PayPalDataCollector-Swift.h

### ISSUE THREAD

**Issue by RayKay91** [braintree/braintree-ios-drop-in#365]
**Integration Details (please complete the following information):**
 - SDK/Library Version: 9.4.0
 - Environment: Sandbox 
 - iOS Version: iOS 15.2
 - Xcode Version:  Xcode 13.2
 - Device : iPhone 13
 - Integration type & version : CocoaPods 1.11.2
 - Development Processor Type: Intel

**Describe the bug**
Description of what the bug is. Please include as many details as possible.

**To Reproduce**
1. Try to build project
1. Build fails because it cannot find file: `PayPalDataCollector-Swift.h` (Error occurs in `BTDropInResult.m`)

**Screenshots**

<img width="1049" alt="Screenshot 2022-02-02 at 12 05 21" src="https://user-images.githubusercontent.com/61206305/152150465-f1ef81d6-6a1e-480b-8356-52fa8a89cf09.png">

Although I am using the Pod in a React Native app I don't believe this is causing any problems. Xcode cannot find the file pictured. 
- I've tried looking for it myself but no such file exists in `Braintree/` or `BraintreeDropIn/` despite the presence of a `PayPalDataCollector/` directory. 
- I have also tried installing pod `Braintree/DataCollector` but the issue persists.
- I have tried using a quotation mark import `#import "PayPalDataCollector-Swift.h"`
- I have tried creating a blank `PayPalDataCollector-Swift.h` file in `Braintree/PayPalDataCollector/`

I can build and the drop in works fine if I comment out the code that causes the issue.

**Comment by jaxdesmarais** [comment]
Hello @RayKay91 -

I've tested this via both the demo app in this repo as well as a standalone demo app and am unable to replicate this error. The header's name is generated from our `PayPalDataCollector` module name, followed by "-Swift.h" when it is exposed to Objective-C (you can read more about this process [here](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c)).

Are you able to provide a simple sample project where we can replicate this error? From there, we would be happy to take a look as this error appears to be independent to your configuration.

**Comment by RayKay91** [comment]
Sure: https://github.com/RayKay91/rn-braintree-demo

**Comment by jaxdesmarais** [comment]
@RayKay91 - thanks for sending over that sample project. I've also been able to reproduce this locally with a react native application. It is worth noting, that we do not officially support react native, so we cannot guarantee a timeline/fix for this issue. As a temporary solution, using version `9.1.0` of the Drop-in resolved the issue for me locally. I will let you know when we have an update on the original issue.

**Comment by RayKay91** [comment]
@jaxdesmarais Awesome! Thanks for the help!

I saw one of the older issues mentioning that it could be an option in the future to support React Native. I'd like to add my vote to that if you could relay it to your team 😄 

Thanks again! 🚀

**Comment by RayKay91** [comment]
Hey so sorry @jaxdesmarais have been super busy. 

I can confirm that it resolves the issue and everything seems to be working fine. Thanks again 😄 🥇
