### ISSUE TITLE
Version 9.4.0 Doesn't Allow Use Of Braintree 5.7.0+ on Cocoapods

### ISSUE THREAD

**Issue by mccarron** [braintree/braintree-ios-drop-in#369]
**Integration Details (please complete the following information):**
 - SDK/Library Version: [e.g. 9.4.0]
 - Integration type & version: CocoaPods 1.11.X
 - Development Processor Type: Intel & M1

**Describe the bug**

Appears that the Cocoapods dependency settings for this repo restricts us to upgrade to latest Braintree version. It's locked to the v5.6.X tree today with setting of: `~> 5.6.1`

**To Reproduce - Scenario 1 **
* Have both `Braintree` and `BraintreeDropIn` in your Podfile. 
* Run `pod update`

**To Reproduce - Scenario 2 **

If I try to force it to update with this Podfile: 
```
  pod 'Braintree', '~> 5.7.0' 
  pod 'BraintreeDropIn', '9.4.0'
```
Then I get the following errors with `pod update`: 
```
CocoaPods could not find compatible versions for pod "Braintree/Core":
  In Podfile:
    Braintree (~> 5.7.0) was resolved to 5.7.0, which depends on
      Braintree/Core (= 5.7.0)

    BraintreeDropIn (= 9.4.0) was resolved to 9.4.0, which depends on
      Braintree/Core (~> 5.6.1)

Specs satisfying the `Braintree/Core (= 5.7.0), Braintree/Core (~> 5.6.1)` dependency were found, but they required a higher minimum deployment target.
```

**Expected behavior**
* Expect `Braintree` to update to the latest version `5.7.0`

**Comment by jaxdesmarais** [comment]
Hello @mccarron -

Thanks for using the Braintree Drop-in SDK. You are correct in that our [`Podspec`](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeDropIn.podspec) sets the dependency targets to a specific version range (in this case 5.6.X). This is to ensure that we have a chance to pull in and test minor and major version bumps before release. Are there specific features for 5.7.0 you are looking to utilize in the Drop-in?

Additionally, it is worth noting that the `BraintreeDropIn` pod will automatically pull in the highest possible version of the SDK and you should not need to explicitly include both pods as `Braintree` is already included as a dependancy of the Drop-in.

**Comment by mccarron** [comment]
> This is to ensure that we have a chance to pull in and test minor and major version bumps before release. Are there specific features for 5.7.0 you are looking to utilize in the Drop-in?

Not specifically as 5.7.0 is just a cache bug fix and haven't had an issue with it. But keeping to the latest and greatest bug fixes for a given dependency is important from a security perspective, especially when it comes to credit card payment tools. It's been two weeks since 5.7.0 was released, so I expected you'd have tested this by now and allowed us to update.
