### ISSUE TITLE
Have carthage support removed?

### ISSUE THREAD

**Issue by engrsandeep** [braintree/braintree-ios-drop-in#370]
We had previously used carthage to build, it is not working now? Can you please help?

**Comment by jaxdesmarais** [comment]
Hello @engrsandeep -

Thanks for opening this issue! We can't make any guarantees about adding Carthage support back in as it was removed in version 9 of the Drop-in SDK. I would recommend [commenting on this GitHub issue that is already open](https://github.com/braintree/braintree-ios-drop-in/issues/323) as that is what we are using to track Carthage interest. 

Version 9 of the Drop-in SDK only supports Swift Package Manager and Cocoapods at this time.
