### ISSUE TITLE
Venmo Not getting Drop In back 

### ISSUE THREAD

**Issue by anniemark271983** [braintree/braintree-ios-drop-in#377]
I am not getting called back after opening the Venmo application, Paypal is working fine and getting calls back in the application and also the nonce 

so can you please let me know what is the issue here? 

The below open URL method is called proper while Paypal payment but it's not call while Venmo payment

func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    
    
    print("application option URL->",url)
    if (url.scheme?.hasPrefix("fb"))!
    {
        ApplicationDelegate.shared.application(UIApplication.shared,open: url,sourceApplication: nil,annotation: [UIApplication.OpenURLOptionsKey.annotation])
    } else if (url.scheme?.hasPrefix("google"))!
    {
        return GIDSignIn.sharedInstance.handle(url)
    } else {
        if url.scheme?.localizedCaseInsensitiveCompare("com.<companyname>.<applicationname>.payments") == .orderedSame {
            return BTAppContextSwitcher.handleOpenURL(url)
        }
    }
    
    return false
}

**Comment by sarahkoop** [comment]
HI @anniemark271983 - Could you please re-open this issue using the issue template? The information requested in that template is necessary for our understanding and investigation of the issue.
