### ISSUE TITLE
'BTCardCapabilities' is deprecated: The UnionPay SMS integration is deprecated, as UnionPay can now be processed as a credit card through their partnership with Discover. Use `BTCardClient.tokenizeCard(card: completion:)`

### ISSUE THREAD

**Issue by Sahil-Tops** [braintree/braintree-ios-drop-in#391]
After updating the BraintreeDropIn we started getting this error from the SDK "BTCardCapabilities' is deprecated".
<img width="1038" alt="Screenshot 2023-01-06 at 4 21 44 PM" src="https://user-images.githubusercontent.com/62637562/210998018-5965fe78-e910-4ff8-acca-edad55b125ee.png">

**Comment by scannillo** [comment]
Hi @Sahil-Tops - thank you for reporting this issue in the BraintreeDropIn iOS SDK. This exact issue was already reported in https://github.com/braintree/braintree-ios-drop-in/issues/385. Please follow along for when a fix gets released in that thread.
