### ISSUE TITLE
Navigation bar on BTPaymentSelectionViewController with incorrect colors

### ISSUE THREAD

**Issue by BartlomiejSopalaKarhoo** [braintree/braintree-ios-drop-in#397]
**Integration Details (please complete the following information):**
 - SDK/Library Version: [e.g. 9.8.0]
 - iOS Version: [e.g. iOS 16.2]
 - Xcode Version: [e.g. Xcode 14.2]
 - Device [e.g. iPhone 14 Pro]
 - Integration type & version [CocoaPods]
 - Development Processor Type: [M1/ Apple Silicon]

**Describe the bug**
As a developer I can setup 2 colors related with Navigation bar in BTDropInUICustomization: `barBackgroundColor` and `navigationBarTitleTextColor`. Both colors as correctly applied to 

But on BTPaymentSelectionViewController navigation bar is transparent, so only `navigationBarTitleTextColor` is applied. Because of that UI customisation is difficult, you need to choose one `navigationBarTitleTextColor` for two different background colors. 

**To Reproduce**
1. Setup:
        uiCustomization.barBackgroundColor = .black
        uiCustomization.navigationBarTitleTextColor = .white

On 1 screen title will look perfectly fine, while on `BTPaymentSelectionViewController` will be barely visible.

**Expected behavior**
Title on BTPaymentSelectionViewController should have PrimaryTextColor if backruundColor for this view is not set as 'barBackgroundColor'.

**Screenshots**

<img width="565" alt="Screenshot 2023-02-27 at 18 31 32" src="https://user-images.githubusercontent.com/97114085/221639154-3fc2e5a9-74c3-4f25-b106-5f8323f8d610.png">
<img width="565" alt="Screenshot 2023-02-27 at 18 31 24" src="https://user-images.githubusercontent.com/97114085/221639182-c321b4dd-4f53-40b1-a9dd-f5093720b9d1.png">

**Comment by jaxdesmarais** [comment]
Hello @BartlomiejSopalaKarhoo -

Thanks for reaching out and using the Drop-in SDK.  Can you clarify what value you are passing into the color scheme here:
```
BTDropInUICustomization(colorScheme: VALUE_PASSED_HERE)
```

Since you are using white text on a black background, I think you'd likely want to use `.dark` or `.dynamic` but are currently using `.light`. Is my understanding correct? I want to be sure I am replicating your set up to troubleshoot further.

**Comment by jaxdesmarais** [comment]
If my understanding is correct, I've published a branch here: [fixes-title-color](https://github.com/braintree/braintree-ios-drop-in/tree/fixes-title-color) that fixes this behavior. Feel free to pull down that branch locally and confirm the behavior is now as expected or if you run into any issues.

**Comment by BartlomiejSopalaKarhoo** [comment]
Hi @jaxdesmarais 
Thanks for your support, this is exactly what I want to have. And regarding your question, I'm passing `.light` on purpose. I have, in my case, dark blue navigation bar in light mode as you can see on my second screenshot and I tried to achieve same colors in your drop-in. Thanks for your help.

**Comment by jaxdesmarais** [comment]
This fix was release in [Drop-in version 9.8.1](https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.8.1). Thanks again for reporting this bug and using the SDK. 🚀
