### ISSUE TITLE
Why braintree can not switch to PayPal app

### ISSUE THREAD

**Issue by K999999999** [braintree/braintree-ios-drop-in#40]
### General information

* SDK/Library version: 5.2.0
* Environment: Sandbox
* iOS Version and Device: iOS 10.3 on an iPhone 6 Plus
* Integration type and version: CocoaPods 1.1.1

### Issue description

I just follow the guide to import braintree, but braintree always present SFSafariViewController with PayPal app installed on my iPhone. My app scheme is com.xxx.xxx.payment and I has added com.paypal.ppclient.touch.v1, com.paypal.ppclient.touch.v2, com.paypal.ppclient.touch.v3, com.venmo.touch.v2 in plist. But it seems that braintree only allow pay by SFSafariViewController not PayPal App.

BTAnalyticsMetadata.m
- (BOOL)isPaypalInstalled {
    if ([self.class isAppExtension]) {
        return NO;
    }
    
    UIApplication *sharedApplication = [UIApplication performSelector:@selector(sharedApplication)];
    static BOOL paypalInstalled;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSURL *paypalV1URL = [NSURL URLWithString:@"com.paypal.ppclient.touch.v1://"];
        NSURL *paypalV2URL = [NSURL URLWithString:@"com.paypal.ppclient.touch.v2://"];
        paypalInstalled = [sharedApplication canOpenURL:paypalV1URL] || [sharedApplication canOpenURL:paypalV2URL];
    });
    return paypalInstalled;
}

PPOTCore.m
+ (BOOL)isWalletAppInstalled {
    [PPOTConfiguration updateCacheAsNecessary]; // called by all public methods

    if (iOS_9_PLUS) {
        // Don't check canOpenUrl and don't fire analytics because we can't find out if the app is installed
        return NO;
    }
    else {
        return ([PPOTAppSwitchUtil isAuthenticatorInstalledForTargetAppURLScheme:kPPOTWalletURLSchemeV1] ||
                [PPOTAppSwitchUtil isAuthenticatorInstalledForTargetAppURLScheme:kPPOTWalletURLSchemeV2] ||
                [PPOTAppSwitchUtil isAuthenticatorInstalledForTargetAppURLScheme:kPPOTWalletURLSchemeV3] );
    }
}

**Comment by demerino** [comment]
@K999999999 - thanks for the question!

You're not doing anything wrong - currently we only switch to `SFSafariViewController` on iOS9+. We've made this decision for a variety of reasons (which I won't go into at this time), but the central theme was to offer a consistent and quality experience for customers and developers. At this time, we feel that `SFSafariViewController` gives us what we're looking for.

That being said, we always look for ways to make our SDKs better. We'll be reevaluating how we integrate with the PayPal app later this year.
