### ISSUE TITLE
Crash in braintree dropin

### ISSUE THREAD

**Issue by Aaqibali279** [braintree/braintree-ios-drop-in#408]
### Braintree Drop-in SDK Version

9.8.2

### Environment

Production

### Xcode Version

xcode 13.4

### OS Version & Device

iOS 16

### Integration type

Swfit Package Manager

### Development Processor

Intel

### Describe the bug

Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x9d98 __pthread_kill + 8
1  libsystem_pthread.dylib        0x6ee0 pthread_kill + 288
2  libsystem_c.dylib              0x7a340 abort + 168
3  AppKit                         0xa8a024 -[NSImageISIconRepProvider init] + 14
4  RMMapper                       0x810c -[NSObject(RMCopyable) copyWithZone:] + 100
5  AppKit                         0x1f5a4c __24-[NSImage copyWithZone:]_block_invoke + 72
6  AppKit                         0x1f5650 -[NSImage copyWithZone:] + 252
7  libobjc.A.dylib                0x12444 objc_setProperty_atomic_copy + 52
8  ShareKit                       0x97fc (Missing UUID 3a5c8042a7b8324f90c6f8b54840e775)
9  ShareKit                       0x8740 (Missing UUID 3a5c8042a7b8324f90c6f8b54840e775)
10 ShareKit                       0x805c (Missing UUID 3a5c8042a7b8324f90c6f8b54840e775)
11 ShareKit                       0x7ac0 (Missing UUID 3a5c8042a7b8324f90c6f8b54840e775)
12 ShareKit                       0x2e42c (Missing UUID 3a5c8042a7b8324f90c6f8b54840e775)
13 AppKit                         0xb33978 +[NSSharingService _sharingServiceNamed:allowInactive:] + 76
14 MessageUIMacHelper             0x6098 +[MFMessageComposeViewControllerHelper canPerformMessageSharingService] + 48
15 PPRiskMagnes                   0x2a2d8 _swift_stdlib_malloc_size + 30784
16 PPRiskMagnes                   0x29444 _swift_stdlib_malloc_size + 27052
17 PPRiskMagnes                   0x1a5d4 block_destroy_helper + 2424
18 PPRiskMagnes                   0x1ffb0 block_destroy_helper + 25428
19 Myapp                           0x4b2c80 specialized static PPDataCollector.generateClientMetadataID(_:disableBeacon:isSandbox:data:) + 58 (PPDataCollector.swift:58)
20 Myapp                           0x4b2e20 specialized static PPDataCollector.collectPayPalDeviceData(isSandbox:) + 4373638688 (<compiler-generated>:4373638688)
21 Myapp                           0x4b172c @objc static PPDataCollector.collectPayPalDeviceData(isSandbox:) + 4373632812 (<compiler-generated>:4373632812)
22 Myapp                           0x451144 -[BTDropInResult initWithEnvironment:] + 61 (BTDropInResult.m:61)
23 Myapp                           0x434ca8 __61-[BTDropInController cardTokenizationCompleted:error:sender:]_block_invoke + 249 (BTDropInController.m:249)
24 libdispatch.dylib              0x25f0 _dispatch_call_block_and_release + 32
25 libdispatch.dylib              0x41b4 _dispatch_client_callout + 20
26 libdispatch.dylib              0x126cc _dispatch_main_queue_drain + 928
27 libdispatch.dylib              0x1231c _dispatch_main_queue_callback_4CF + 44
28 CoreFoundation                 0xc6a2c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
29 CoreFoundation                 0x83cb8 __CFRunLoopRun + 2532
30 CoreFoundation                 0x82b34 CFRunLoopRunSpecific + 600
31 HIToolbox                      0x32338 RunCurrentEventLoopInMode + 292
32 HIToolbox                      0x320b4 ReceiveNextEventCommon + 564
33 HIToolbox                      0x31e68 _BlockUntilNextEventMatchingListInModeWithFilter + 72
34 AppKit                         0x4151c _DPSNextEvent + 860
35 AppKit                         0x3fe14 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
36 AppKit                         0x31fe0 -[NSApplication run] + 596
37 AppKit                         0x36fc NSApplicationMain + 1132
38 AppKit                         0x2d9640 _NSApplicationMainWithInfoDictionary + 22
39 UIKitMacHelper                 0x53c0 UINSApplicationMain + 1276
40 UIKitCore                      0x3c2c UIApplicationMain + 164
41 Myapp                           0x81ac main + 24 (AppDelegate.swift:24)
42 ???                            0x103ac908c (Missing)
Thread
0  libsystem_kernel.dylib         0x372c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x33ac _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x2080 start_wqthread + 8
Thread
0  libsystem_kernel.dylib         0x372c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x33ac _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x2080 start_wqthread + 8
com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x18b0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1d20 mach_msg + 76
2  CoreFoundation                 0x852c0 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0x83770 __CFRunLoopRun + 1180
4  CoreFoundation                 0x82b34 CFRunLoopRunSpecific + 600
5  Foundation                     0x64100 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  Foundation                     0xef0cc -[NSRunLoop(NSRunLoop) runUntilDate:] + 124
7  UIKitCore                      0x53a8 -[UIEventFetcher threadMain] + 156
8  Foundation                     0x5c60c __NSThread__start__ + 808
9  libsystem_pthread.dylib        0x726c _pthread_start + 148
10 libsystem_pthread.dylib        0x208c thread_start + 8
com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0x18b0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1d20 mach_msg + 76
2  FirebaseCrashlytics            0x1a520 FIRCLSMachExceptionServer + 104
3  libsystem_pthread.dylib        0x726c _pthread_start + 148
4  libsystem_pthread.dylib        0x208c thread_start + 8
Thread
0  libsystem_kernel.dylib         0x506c __semwait_signal + 8
1  libsystem_c.dylib              0xefc8 nanosleep + 220
2  libsystem_c.dylib              0x19b78 sleep + 52
3  Sentry                         0x1b9bc monitorCachedData + 700
4  libsystem_pthread.dylib        0x726c _pthread_start + 148
5  libsystem_pthread.dylib        0x208c thread_start + 8
SentryCrash Exception Handler (Secondary)
0  libsystem_kernel.dylib         0x18b0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1d20 mach_msg + 76
2  libsystem_kernel.dylib         0x2a9d8 thread_suspend + 96
3  Sentry                         0x291f8 handleExceptions + 128
4  libsystem_pthread.dylib        0x726c _pthread_start + 148
5  libsystem_pthread.dylib        0x208c thread_start + 8
SentryCrash Exception Handler (Primary)
0  libsystem_kernel.dylib         0x18b0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1d20 mach_msg + 76
2  Sentry                         0x29224 handleExceptions + 172
3  libsystem_pthread.dylib        0x726c _pthread_start + 148
4  libsystem_pthread.dylib        0x208c thread_start + 8
io.sentry.app-hang-tracker
0  libsystem_kernel.dylib         0x506c __semwait_signal + 8
1  libsystem_c.dylib              0xefc8 nanosleep + 220
2  Foundation                     0xf2784 +[NSThread sleepForTimeInterval:] + 160
3  Sentry                         0x93ec -[SentryANRTracker detectANRs] + 772
4  Foundation                     0x5c60c __NSThread__start__ + 808
5  libsystem_pthread.dylib        0x726c _pthread_start + 148
6  libsystem_pthread.dylib        0x208c thread_start + 8
com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x18b0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1d20 mach_msg + 76
2  CoreFoundation                 0x852c0 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0x83770 __CFRunLoopRun + 1180
4  CoreFoundation                 0x82b34 CFRunLoopRunSpecific + 600
5  CFNetwork                      0x26b638 _CFURLStorageSessionDisableCache + 39472
6  Foundation                     0x5c60c __NSThread__start__ + 808
7  libsystem_pthread.dylib        0x726c _pthread_start + 148
8  libsystem_pthread.dylib        0x208c thread_start + 8
com.apple.NSEventThread
0  libsystem_kernel.dylib         0x18b0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1d20 mach_msg + 76
2  CoreFoundation                 0x852c0 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0x83770 __CFRunLoopRun + 1180
4  CoreFoundation                 0x82b34 CFRunLoopRunSpecific + 600
5  AppKit                         0x1ae100 _NSEventThread + 196
6  libsystem_pthread.dylib        0x726c _pthread_start + 148
7  libsystem_pthread.dylib        0x208c thread_start + 8
Thread
0  libsystem_kernel.dylib         0x372c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x33ac _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x2080 start_wqthread + 8
com.google.Maps.LabelingBehavior
0  libsystem_kernel.dylib         0x18b0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1d20 mach_msg + 76
2  CoreFoundation                 0x852c0 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0x83770 __CFRunLoopRun + 1180
4  CoreFoundation                 0x82b34 CFRunLoopRunSpecific + 600
5  Foundation                     0x64100 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  Bart                           0x9691b0 -[GMSx_GTMSimpleWorkerThread main] + 59104
7  Foundation                     0x5c60c __NSThread__start__ + 808
8  libsystem_pthread.dylib        0x726c _pthread_start + 148
9  libsystem_pthread.dylib        0x208c thread_start + 8
Thread
0  libsystem_kernel.dylib         0x372c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x33ac _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x2080 start_wqthread + 8
Thread
0  libsystem_kernel.dylib         0x372c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x33ac _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x2080 start_wqthread + 8
com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x18b0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1d20 mach_msg + 76
2  CoreFoundation                 0x852c0 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0x83770 __CFRunLoopRun + 1180
4  CoreFoundation                 0x82b34 CFRunLoopRunSpecific + 600
5  CoreFoundation                 0x10fcc8 CFRunLoopRun + 64
6  CoreMotion                     0x198320 CLClientCreateIso6709Notation + 229176
7  libsystem_pthread.dylib        0x726c _pthread_start + 148
8  libsystem_pthread.dylib        0x208c thread_start + 8

### To reproduce

no steps

### Expected behavior

no crash

**Comment by jaxdesmarais** [comment]
Hello @Aaqibali279 -

We will need a bit more details from you as so far I have been unable to replicate this crash in the demo app provided in this repository. Additionally it is worth noting that Apple requires all submissions to be made to the App Store using [Xcode 14.1+ as of April 25th](https://developer.apple.com/news/?id=jd9wcyov).

Please confirm the following so we can troubleshoot further:

1. Do you still run into the crash using Xcode 14.1+ (per Apple's requirement)?
2. Can you replicate the crash in our [demo app](https://github.com/braintree/braintree-ios-drop-in/tree/master/Demo)? If so please provided the steps we can follow to replicate the crash.
3. If you cannot replicate the crash in our demo app, please provide a sample project you are using to replicate the crash along with the steps we can follow to replicate the crash in your sample project.
