### ISSUE TITLE
Can't build app 'unarchiveObjectWithData:' is deprecated

### ISSUE THREAD

**Issue by andrii-lisovskiy** [braintree/braintree-ios-drop-in#412]
### Braintree Drop-in SDK Version

8.2.0

### Environment

Both

### Xcode Version

14.3

### OS Version & Device

iPhone 13 Pro - 16.4.1(a)

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

Cannot build my app not to Simulator, nor to device.

### To reproduce

Everything is on screenshots

### Expected behavior

I will be able to build app.

### Screenshots

<img width="398" alt="Screenshot 2023-05-10 at 17 02 51" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/6d4d43ae-48ba-4d47-ba7c-4d44b55cf479">
<img width="234" alt="Screenshot 2023-05-10 at 17 03 03" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/847d171d-0e25-4efe-9bb5-faa9e67de61a">
<img width="683" alt="Screenshot 2023-05-10 at 17 03 17" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/03890feb-8a2c-4c81-a670-39e96857ce5a">

**Comment by scannillo** [comment]
👋 This is resolved in the latest major version. Please update to 9.8.2

**Comment by andrii-lisovskiy** [comment]
So, in my Podfile I have removed `pod "Braintree/Apple-Pay"` and left `pod "BraintreeDropIn"`. This fixed my problem.
