### ISSUE TITLE
How to read the BTCard information such as card holder name and expire date from the BTDropInResult?

### ISSUE THREAD

**Issue by johndev8964** [braintree/braintree-ios-drop-in#413]
### Is your feature request related to a problem? Please describe.

I want to read the card information such as card holder name and expire date in BTDropInResult.
How can I do it?
Thanks.

**Comment by scannillo** [comment]
👋 Hello - GitHub issues is for feature requests or bugs found in the SDK. For help troubleshooting your specific integration, reach out to our Developer Support team - https://developer.paypal.com/braintree/help.
