### ISSUE TITLE
dropincontroller + 3ds

### ISSUE THREAD

**Issue by antons81** [braintree/braintree-ios-drop-in#43]
### General information

* SDK/Library version: 4.8.3
* Environment: prod
* iOS Version and Device: 10.3
* Integration type and version: cocoapods 1.2.1

### Issue description

Hello Support, I am using dropincontroller and trying to authorize credit card with 3ds but without success.
`  BTDropInRequest *request = [[BTDropInRequest alloc] init];
                    request.applePayDisabled = YES;
                    request.currencyCode = @"GBP";
                    request.amount = [NSString stringWithFormat:@"£%.02f",[buyOrder getTotalAmount]];
                    request.threeDSecureVerification = YES;
                    
               
                  self.threeDSecure = [[BTThreeDSecureDriver alloc] initWithAPIClient:self.braintree delegate:self];
                    

                    self.dropInViewController = [[BTDropInController alloc] initWithAuthorization:clientToken request:request handler:^(BTDropInController * _Nonnull controller, BTDropInResult * _Nullable result, NSError * _Nullable error) {
                        
                        if (error != nil) {

                            [error show];
                            [self dismissDropIn];
                            
                        } else if (result.cancelled) {

                            [self dismissDropIn];
                            
                        } else {
                            
                            [BTDropInResult fetchDropInResultForAuthorization:self.clientToken handler:^(BTDropInResult * _Nullable result, NSError * _Nullable error) {
                                
                                if (error != nil) {
                                    NSLog(@"%@", error.localizedDescription);
                                    return;
                                }
                                
                                NSLog(@"NONCE %@", result.paymentMethod.nonce);
                                
                            }];
                            

                            [self.threeDSecure verifyCardWithNonce:result.paymentMethod.nonce amount:[NSDecimalNumber decimalNumberWithString:[NSString stringWithFormat:@"£%.02f",[buyOrder getTotalAmount]]] completion:^(BTThreeDSecureCardNonce * _Nullable tokenizedCard, NSError * _Nullable error) {
                                
                                if (error != nil) {
                                    NSLog(@"%@", error.localizedDescription);
                                    return;
                                }
                                
                                NSLog(@"NONCE %@", tokenizedCard.nonce);
                                //[self collectDataForServer:tokenizedCard.nonce];
                                
                            }];

                        }
                    }];

                    [[self presentingViewController] presentViewController:self.dropInViewController animated:YES completion:nil];
`

Every time I am clikcing on existing card or adding new one the app crashing on braintree methods handlers (SDK methods) with error Nan write in JSON and 3ds widow not appears. What could be the issue?

**Comment by sdcoffey** [comment]
Hey @antons81,

Can you provide a stack trace that you're seeing? That will help us diagnose the problem a little more accurately. Thanks!

**Comment by antons81** [comment]
Hello, Steve. The issue actaly fixed, Now I see barclays 3ds window. Need to be implement second 3ds auth with BTDropinResult and send valid amount. There was crash because it's cannot read amount decimal. Now all ok.
