### ISSUE TITLE
Allow WKWebView to be inspectable 

### ISSUE THREAD

**Issue by Hero-Darrel** [braintree/braintree-ios-drop-in#437]
### Is your feature request related to a problem? Please describe.

As of iOS 16.4 a new WKWebView property called **inspectable** was added with a default of false. Unfortunately this makes web views unaccessible to automated tests. Since we use this library in our app, we are not able to update this property locally. Here's some more info on this new property: https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/

### Describe the solution you'd like.

Requesting that all WKWebViews enable the inspectable property or have a facility (env variable maybe) where we can manually enable it when running automated tests. Maybe it's just enabled for debug builds?

**Comment by jaxdesmarais** [comment]
Hey @Hero-Darrel -

We don't currently use `WKWebView` in any of the web based flows for the Drop-in. Instead we use `ASWebAuthenticationSession` and `SFSafariViewController`. Would you mind clarifying what version of the SDK you are using, which flow you are unable to debug using the inspector, and what iOS version you are running into this issue with?

**Comment by Hero-Darrel** [comment]
Hi Jax .. Thanks for the quick reply. For context, I'm using appium for automated testing. My understanding from our devs is that all of our payment stuff comes from the braintree-ios-drop-in library and one of our tests needs to login to paypal. When the webview launches, I am not able to interact with any of the elements (like the paypal login/password fields) because they are not exposed in the dom. After further investigation, I found that webkit post about the new **inspectable** property in iOS 16.4 and asked our devs to implement it, but they said they couldn't because the webview is being displayed from the braintree library. Which lead me to create this enhancement request.

Sure enough, when I dropped back to a simulator with iOS 16.2, then I was able to inspect the webview to find the paypal login/password elements. I should be able to get the page source between 16.2 and 17.0 this afternoon so you can see what I'm talking about if that will help. We are using Braintree 5.24.0 and BraintreeDropin 9.10.0

**Comment by Hero-Darrel** [comment]
[mobile dom.zip](https://github.com/braintree/braintree-ios-drop-in/files/13666008/mobile.dom.zip)
@jaxdesmarais Attached are 2 files showing what's inspectable between ios 16.2 and iOS 17.0

**Comment by jaxdesmarais** [comment]
Hey @Hero-Darrel -

We do not use appium on the Braintree side, but we do have [UITests around interacting with the PayPal webview](https://github.com/braintree/braintree-ios-drop-in/blob/679100e5781c364adcdd37ffb2d597181286125b/Demo/UITests/BraintreeDropIn_UITests.swift#L543). 

Additionally I was able to run our demo app on an iPhone 15 simulator running iOS 17.0 and am able to interact with both the email and password fields elements as seem below in the Safari web inspector:
![Screenshot 2023-12-14 at 9 14 59 AM](https://github.com/braintree/braintree-ios-drop-in/assets/20733831/30069809-01ec-45e2-83a6-7db18ffefcf1)

It may be worth reaching out to the appium to see if this bug has been reported by other users or if there is additional setup needed.

**Comment by Hero-Darrel** [comment]
Thanks for the feedback Jax. I did some additional investigation and it seems like Apple may have added the same functionality to ASWebAuthenticationSession and SFSafariViewController by accident but then fixed it in iOS 17.2. I was able to confirm that I am successfully able to inspect webviews again with an iOS 17.2 simulator. 

So we can go ahead and close this, but just a heads up that it's broken between iOS 16.4 and 17.0.1. Also if you guys ever do switch to WKWebView, please include a way to turn on the inspectable property so that webviews can still be inspected.

Thanks again for your help with this.

**Comment by jaxdesmarais** [comment]
Glad to hear you are now able to inspect the elements as expected and appreciate the heads up on that Apple bug. We have no plans to move to `WKWebView` as it does not allow the customers to see the URL where they are checking out, which is important when making a payment! If our plans ever do change we will always work to ensure merchants can troubleshoot and run tests as expected.

I'll go ahead and close this issue, but if you have questions about the SDK in the future please feel free to reach back out!
