### ISSUE TITLE
Slovak language support

### ISSUE THREAD

**Issue by matejsemancik** [braintree/braintree-ios-drop-in#439]
### Describe the solution you'd like.

I would like to see support for Slovak language, as the Android counterpart already has the support: https://github.com/braintree/braintree-android-drop-in/blob/main/Drop-In/src/main/res/values-sk/strings.xml

**Comment by scannillo** [comment]
👋 Hi @matejsemancik - thank you for opening this issue (and PR #438) with us. I see our Android and JS Drop-In SDKs do support Slovak. Let me check in with our localization team that this is a language we indeed are supporting going forward, and if so, I will create a ticket for us to internally track the progress of adding support for it to the iOS SDK!

**Comment by scannillo** [comment]
Hi @matejsemancik - Slovak language support was added in version [9.11.0](https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.11.0). Thank you for raising this request to us, and please let us know if you encounter any other issues in the future!
