### ISSUE TITLE
3Dsecure web view blank 

### ISSUE THREAD

**Issue by franci98** [braintree/braintree-ios-drop-in#442]
### Braintree Drop-in SDK Version

9.10.1

### Environment

Sandbox

### Xcode Version

xCode 15.1

### OS Version & Device

iPhone 8 iOS 16.7 and others

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

From this morning on the 3DS logic stopped working on our iOS SDK.
The web view which should open the website is blank and we have no option to get any useful info on why this happened.
I am also adding a video of the behavior.

https://github.com/braintree/braintree-ios-drop-in/assets/19323463/306640b6-eac4-4fc9-9e8c-2a801188c5b0

### To reproduce

On our app the video is showing the steps to reproduce

https://github.com/braintree/braintree-ios-drop-in/assets/19323463/306640b6-eac4-4fc9-9e8c-2a801188c5b0

### Expected behavior

The webview should open the OTP form to put in the requested data and continue the flow

### Screenshots

https://github.com/braintree/braintree-ios-drop-in/assets/19323463/306640b6-eac4-4fc9-9e8c-2a801188c5b0

**Comment by jaxdesmarais** [comment]
Hello @franci98 -

I am not seeing this issue with the 3D Secure webview being blank for Visa test card ending in `4111` or Mastercard test card ending in `1096`. Is there anything being output to the console in Xcode or are they any specific setup details you can share so we can replicate this issue? Alternatively, if you are able to send over a small test project we'd be happy to take a look.

**Comment by franci98** [comment]
We fixed the issue. It was on our backend.
