### ISSUE TITLE
Deprecated API `UIGraphicsBeginImageContextWithOptions` still in use for iOS 17+

### ISSUE THREAD

**Issue by SukhKalsi** [braintree/braintree-ios-drop-in#446]
### Is your feature request related to a problem? Please describe.

Apple developer documentation: https://developer.apple.com/documentation/uikit/1623912-uigraphicsbeginimagecontextwitho

Currently this deprecated API is used in the following:

https://github.com/braintree/braintree-ios-drop-in/blob/b4759969e805bb82209e9a6a555bf16f1e547af1/Sources/BraintreeDropIn/Vector%20Art/BTUIKVectorArtView.m#L25

https://github.com/braintree/braintree-ios-drop-in/blob/b4759969e805bb82209e9a6a555bf16f1e547af1/Sources/BraintreeDropIn/Components/BTUIKCardListLabel.m#L34

This API can cause potential crashes. So far this package seems to be fine (for now) however the usage of this API is now deprecated.

Here is an Apple Developer Forums post on the potential crash that can occur currently - https://forums.developer.apple.com/forums/thread/733326 . This may get progressively worse as newer iOS versions are released in future.

### Describe the solution you'd like.

As per Apple API reference, this API has been deprecated in favour of `UIGraphicsImageRenderer`, `UIGraphicsImageRendererContext` & `UIGraphicsImageRendererFormat` which are all available from iOS 10+

https://developer.apple.com/documentation/uikit/uigraphicsimagerenderer
https://developer.apple.com/documentation/uikit/uigraphicsimagerenderercontext
https://developer.apple.com/documentation/uikit/uigraphicsimagerendererformat

**Comment by jaxdesmarais** [comment]
Hey @SukhKalsi -

Thanks so much for using the SDK and alerting us of the deprecated API usage. I've created internal ticket DTBTSDK-3749 for resolving this on our end. We will keep you updated here once that work has been prioritized and we have a PR to address this.

**Comment by jaxdesmarais** [comment]
Hey @SukhKalsi -

This was released in [version 9.12.1](https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.12.1). Thanks again for bringing this to our attention. 🚀
