### ISSUE TITLE
Apple Pay button should be hidden if Apple Pay payments are not possible on the device 

### ISSUE THREAD

**Issue by mauh-akra** [braintree/braintree-ios-drop-in#45]
### General information

* SDK/Library version: 5.2.0
* Environment: Production
* iOS Version and Device: iOS 9 +
* Integration type and version:  CocoaPods 1.2.0

### Issue description

> Unless you opt out, by setting showApplePayPaymentOption = false, Drop-In will show Apple Pay as a payment option as long as it is enabled in the control panel **and the customer's device supports paying with your supported card networks**.

--> this doesn't seem to work properly. The Apple Pay is configured, it's working on staging and on production, but the option for Apple Pay is appearing also on devices in countries, that don't support apple pay. 
The work around is to exclude apple pay manually by setting BTDropInRequest.applePayDisabled (if apple pay is not supported on the device), but since the documentation is stating that this should be handled by default, this might be confusing.

**Comment by demerino** [comment]
@mauh-akra 
Thanks for the feedback, your `work around` is the intended approach that gives developers the ability to control the visibility. We currently only check if it is enabled in the Control Panel AND the flag is not disabled: https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeDropIn/BTPaymentSelectionViewController.m#L220

**Proposal**
Update the docs to remove `and the customer's device supports paying with your supported card networks` and adding a section that recommends checking if the device/country is supported along with an example.

Let us know if something else makes sense and feel free to share an example of the `does support` check if you're able to.

**Comment by mauh-akra** [comment]
Thank you for your response, I fully agree with your proposal - please update the docs and the code snippet I use now for checking whether to show Apple Pay button, or not,  is following:
```
- (BOOL) applePaySupported {  
    return [PKPaymentAuthorizationViewController canMakePayments] && [PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:@[PKPaymentNetworkAmex, PKPaymentNetworkVisa, PKPaymentNetworkMasterCard]];  
}  
```  
and later on the `BTDropInRequest` object setting  
`request.applePayDisabled = ![self applePaySupported];`
