### ISSUE TITLE
Privacy manifest lacks purpose of collection for payment info data type

### ISSUE THREAD

**Issue by dmazzoni** [braintree/braintree-ios-drop-in#450]
### Braintree Drop-in SDK Version

9.12.1

### Environment

Both

### Xcode Version

Xcode 15.2

### OS Version & Device

Any

### Integration type

CocoaPods

### Development Processor

Both

### Describe the bug

The privacy manifest discloses that the Drop-In SDK collects the `NSPrivacyCollectedDataTypePaymentInfo` data type, but the only specified purpose is an [empty string](https://github.com/braintree/braintree-ios-drop-in/blob/fe770e528dc52620eec5149109b15dc0fd626ad4/Sources/BraintreeDropIn/PrivacyInfo.xcprivacy#L27).

### To reproduce

See the SDK's privacy manifest file.

### Expected behavior

I would expect the `NSPrivacyCollectedDataTypePurposes` array to contain non-empty strings that represent valid purposes listed in Apple's [documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests).

**Comment by KunJeongPark** [comment]
Thank you for letting us know. This was an oversight and we will release a fix shortly.

**Comment by KunJeongPark** [comment]
Thank you for your patience. We just released a fix with version 9.12.2.
