### ISSUE TITLE
Braintree iOS drop-in not show device language while Braintree android drop-in show device language

### ISSUE THREAD

**Issue by engrsandeep** [braintree/braintree-ios-drop-in#50]
Hi,

We are developing a multilingual app. We are integrating Braintree drop-in for android and iOS.  Braintree iOS drop-in not showing device language while Android drop-in works well. Can you please help us.

Many thanks.

**Comment by demerino** [comment]
@engrsandeep We'll need some more information in order to help you. How are you integrating Braintree Drop-in (Cocoapods, Carthage?) and what version of the SDK are you using?

It would also be helpful to know how you are testing and on what version of iOS you are testing on.

**Comment by engrsandeep** [comment]
@demerino We are using drop-in 5.0 and testing on iPhone 6s 10.3. 
We have integrated braintree drop in ionic framework with plugin https://github.com/Taracque/cordova-plugin-braintree

It shows device language in braintree drop-in for Android but not for iOS.
Can you please help.

**Comment by demerino** [comment]
@engrsandeep 

It looks like you have already commented on an issue with the plugin: https://github.com/Taracque/cordova-plugin-braintree/issues/28#issuecomment-319282831

I suggest trying to manually include the BTUI.strings bundle so that your app can find them at runtime. Otherwise the application falls back to english if the strings can not be found. Our strings are here: https://github.com/braintree/braintree-ios-drop-in/tree/master/BraintreeUIKit/Localization

**Comment by engrsandeep** [comment]
@demerino this is already included. see here 
![image](https://user-images.githubusercontent.com/10007250/28857714-06cf4d68-7769-11e7-8189-1bf0ce9f2c2f.png)

**Comment by demerino** [comment]
Can you see if the language changes for you in our Demo app (included in this repo)? Let us know if that works. 

You'll need to do more than include the files in our directory, you also need to ensure that they are copied to your bundle: see `Copy Bundle Resources` under `Build Settings`.

**Comment by engrsandeep** [comment]
@demerino i see like this in xcode.
![image](https://user-images.githubusercontent.com/10007250/28885318-206cff1c-77d3-11e7-97b3-7188ddb97d1b.png)

**Comment by demerino** [comment]
_Whoops_

I meant `Build Phases`, you should see:
![screen shot 2017-08-02 at 10 10 34 am](https://user-images.githubusercontent.com/7817434/28885490-ec249ca0-776a-11e7-8278-6efc66b05b62.png)

If not, then add `BTUI.strings`.

**Comment by engrsandeep** [comment]
@demerino  Added BTUI.string and worked. 
Many Thanks for help.

One question, what should i do that it auto include in Build Phased instead manually adding

**Comment by engrsandeep** [comment]
also text mixing with cancel button. I think it either need smaller text or must convert in multiline.
![image](https://user-images.githubusercontent.com/10007250/28886444-273dda56-77d7-11e7-8040-3609ef01a583.png)

**Comment by demerino** [comment]
Great! Make sure you have the newest version of Braintree Drop-In (it should have the fixes for the next in your screenshot).

The way to get everything automatically is to use Cocoapods. Otherwise you'll have to do it manually at least once.

Note that in the README we recommend and fully support Carthage and Cocoapods for integrations. https://github.com/braintree/braintree-ios-drop-in#getting-started

**Comment by engrsandeep** [comment]
Thanks @demerino for help.

**Comment by engrsandeep** [comment]
@demerino i have tested and it worked in simulator/debug mode. But when i published to ituneconnect and tested from TestFlight. It do not work.  I have added BTUI strings for 5 languages in Build phases. It works fine when check on simulator from xcode. but not working after upload on ituneconnect. Please help.
![image](https://user-images.githubusercontent.com/10007250/29240936-d08ccab0-7f8c-11e7-86c9-b1d353f8b8df.png)

**Comment by demerino** [comment]
@engrsandeep What are the results when buildings to a device from Xcode (not through TestFlight)?

I'm not sure what you mean by `I have added BTUI strings for 5 languages in Build phases` - could you explain more?

**Comment by engrsandeep** [comment]
@demerino it works fine when i run app on iPhone directly from Xcode. But after archiving and pushing to ituneconnect and tested from Test Flight on same device. It not working.

Last time you had asked to include BTUI string manually in xcode build phases. I did & after that it started work on simulator or directly run app on device from Xcode. 

Please help.

**Comment by demerino** [comment]
I'm not sure what the specific issue would be, but here are some suggestions:

- Ensure your app has the selected languages supported in iTunesConnect
- Try deleting the app and selecting your language before downloading from TestFlight

**Comment by engrsandeep** [comment]
@demerino We have already configured iTunesConnect with 5 languages, and tested for french user as well but i tried your method now but still not working.
![img_0788](https://user-images.githubusercontent.com/10007250/29346623-28d1c5c0-8264-11e7-8e18-2fbedcc86f10.PNG)

**Comment by engrsandeep** [comment]
@demerino i have fixed it... There was some conflict issue. Thank you for help.

**Comment by bhaveshdaswani93** [comment]
can you provide description on how you fixed the issue as I am implementing this library using react native your reply would be helpful

**Comment by xavieramoros** [comment]
@bhaveshdaswani93 I ended up here after implementing this library in React Native (0.60.6), using this wrapper: https://github.com/wgltony/react-native-braintree-dropin-ui

What worked for me was:
* Add in podfile `pod 'BraintreeDropIn/UIKit'` (don't forget do to a `pod install` afterwards).

* Drag translation files to XCode
All the translation files can be found here: https://github.com/braintree/braintree-ios-drop-in/tree/master/BraintreeUIKit/Localization

So basically drag the language that you want to support, for example `es.lproj` file, into to Xcode, adding it to all the targets that you want: 
![image](https://user-images.githubusercontent.com/347030/83775139-e8d01180-a686-11ea-84d2-09f247128194.png)
![image](https://user-images.githubusercontent.com/347030/83775258-00a79580-a687-11ea-8170-53cb71209914.png)

After doing just that I the Braintree Dropin would use the system language and show correctly translated..
