### ISSUE TITLE
UnionPay beta build warning

### ISSUE THREAD

**Issue by plerma** [braintree/braintree-ios-drop-in#51]
### General information

* SDK/Library version: Braintree (4.7.4), BraintreeDropIn (5.1.0)
* Integration type and version: CocoaPods 1.2.1

### Issue description

Since this framework is dependant of UnionPay (although it is in beta), we are getting a warning in the pragma message in `BTCardClient+UnionPay` (line 1). How can we avoid this?

Thanks!

**Comment by demerino** [comment]
We've removed the warning from the SDK (Braintree 4.9.0). Note that UnionPay is still in Beta, as noted in our docs: https://developers.braintreepayments.com/guides/unionpay/overview
