### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by ramunasjurgilas** [braintree/braintree-ios-drop-in#53]
/Users/Pods/Braintree/BraintreeCore/BTAPIClient.m:190:45: Object of type 'NSNumber *' is not compatible with dictionary value type 'NSString *'

190 line: ->              parameters:@{@"default_first": @(defaultFirst),

**Comment by bluk** [comment]
I believe you've solved this issue from the followup issue #54 later. If not, please leave a comment and we can reopen. For anyone else, you will need the latest version of `braintree-ios`. Usually a `pod repo update` and `pod update Braintree` or a general `pod update` should work to solve this issue.
