### ISSUE TITLE
Build error for UIApplicationOpenURLOptionsSourceApplicationKey

### ISSUE THREAD

**Issue by ramunasjurgilas** [braintree/braintree-ios-drop-in#54]
/Users/Pods/Braintree/BraintreeCore/BTAppSwitch.m:40:87: 'UIApplicationOpenURLOptionsSourceApplicationKey' is only available on iOS 9.0 or newer

Using in the project with Swift 4.0 and Xcode 9.

**Comment by bluk** [comment]
Are you using a deployment target of iOS 9.0 or higher? iOS Drop-In requires a deployment target of iOS 9.0 or higher.

**Comment by bluk** [comment]
Also, do you have a platform of at least 9.0 declared in your `Podfile` like `platform :ios, '9.0'`?

**Comment by bluk** [comment]
As a temporary workaround, you can try adding a [post_install](https://guides.cocoapods.org/syntax/podfile.html#post_install) step to your Podfile as [suggested by @mdelamata here](https://github.com/braintree/braintree_ios/issues/353#issuecomment-332521468). We are working on a fix.

**Comment by deejkelms** [comment]
I used the `post_install` workaround mentioned above by @bluk / @mdelamata which got me past the `UIApplicationOpenURLOptionsSourceApplicationKey` build error, but ran into a new build error in `BTPaymentSelectionViewController`:

**Error:**  
```BTPaymentSelectionViewController.m:255:49: This block declaration is not a prototype```

**Image:**   
![image](https://user-images.githubusercontent.com/15862968/30981484-82bbfd48-a452-11e7-801a-3b28d9ee8e36.png)

Also, for the record:
Deployment Target: `10.0`
Platform declared in Podfile: `ios, 10.0`
XCode 9.0
Swift 4.0

**Comment by bluk** [comment]
@ramunasjurgilas The original issue mentioned with `UIApplicationOpenURLOptionsSourceApplicationKey ` should be resolved with [Braintree iOS SDK 4.9.3](https://github.com/braintree/braintree_ios/releases/tag/4.9.3).

@deejkelms This should be resolved with [Braintree Drop-In 5.2.3](https://github.com/braintree/braintree-ios-drop-in/releases/tag/5.2.3) released earlier today.

In both cases, you may have to `pod repo update` and `pod update` to get the latest version of the pods in your local CocoaPods project. If you are still running into an issue, please leave a comment or open a new issue. Thanks for your patience.

**Comment by ramunasjurgilas** [comment]
@bluk Thanks for the effort updating code. I will try in a minute. Sorry, that I did not respond earlier as I was on vacations.
