### ISSUE TITLE
Label change for "Scan with card.io"

### ISSUE THREAD

**Issue by jonathon-oodar** [braintree/braintree-ios-drop-in#58]
Since our users aren't familiar with the name 'card.io', is it possible to change the button string "Scan with card.io" to something a little more conceptually friendly such as "Scan with camera"?

**Comment by demerino** [comment]
That seems reasonable - we'll look into it for the next release.

**Comment by demerino** [comment]
We're getting the translations for the new string. We'll update when it is released.

**Comment by demerino** [comment]
PR: https://github.com/braintree/braintree-ios-drop-in/pull/67

**Comment by demerino** [comment]
This was updated in 5.3.0
