### ISSUE TITLE
Drop in UI unresponsive on tapping venmo

### ISSUE THREAD

**Issue by alexbrashear** [braintree/braintree-ios-drop-in#60]
### General information

* SDK/Library version: Braintree = 4.9.3, Drop In = 5.2.2
* Environment: Sandbox
* iOS Version and Device: iOS 11
* Integration type and version:  CocoaPods 1.2

### Issue description

Hi!

I have been authorized by Braintree to accept Venmo payments and have followed the integration steps outlined here: https://developers.braintreepayments.com/guides/venmo/client-side/ios/v4

When I open up the drop in UI and tap Venmo nothing happens. It just highlights the button briefly and then returns to normal. I feel like I am missing something obvious but have been over it several times with no luck. Any help I could get in debugging this would be much appreciated, thanks!

**Comment by bluk** [comment]
Hello,

When executing:
```
self.venmoDriver?.authorizeAccountAndVault(false, completion: { (venmoAccount, error) in
    guard let venmoAccount = venmoAccount else {
            print("Error: \(error)")
            return
        }
...
})
```
is there an error in the callback that is passed back?

One specific error that has come up recently is for new Xcode 9 projects, you may not have a value in `CFBundleDisplayName` in your Info.plist which is required.

**Comment by alexbrashear** [comment]
@bluk adding a bundle display name solved the problem, thanks so much for your help!

**Comment by gopendra** [comment]
Hello,

when using venmo payment method (javascript sdk) its not opening app or website on iOS 

if (venmoInstance.hasTokenizationResult()) {
								    venmoInstance.tokenize(function (tokenizeErr, payload) {
								      if (tokenizeErr) {
								        handleVenmoError(tokenizeErr);
								      } else {
								        handleVenmoSuccess(payload);
								      }
								    });

								    return;
								 }

whereas when opening same into chrome browser it opens a new tab with venmo website.

i also userd : allowNewBrowserTab: false,  for braintree.venmo.create but nothings happened for this too. 
Thanks,

**Comment by bluk** [comment]
@gopendra This seems more like a question for [braintree-web](https://github.com/braintree/braintree-web). I would double check the [browser requirements](https://developers.braintreepayments.com/guides/venmo/client-side/javascript/v3). If you're still encountering an issue, please feel free to contact [Braintree Support](https://developers.braintreepayments.com/forms/contact).
