### ISSUE TITLE
iPhone X UI Support

### ISSUE THREAD

**Issue by shpuntov** [braintree/braintree-ios-drop-in#62]
### General information

* SDK/Library version: 5.2.3
* Environment: Production
* iOS Version and Device: iOS 11.1 on an iPhone X
* Integration type and version: CocoaPods 1.3.1

### Issue description

As an iPhone X user, I'd want `BTDropInController` to be displayed in a safe area:

![simulator screen shot - iphone x - 2017-11-16 at 18 36 31](https://user-images.githubusercontent.com/1327944/32896669-1717b272-cafd-11e7-8e86-be8f4cd967f8.png)

**Comment by demerino** [comment]
@shpuntov Thanks for pointing out this issue. We'll look into getting this fixed.

**Comment by shpuntov** [comment]
Also just noted — **Cancel** navigation button in this dialog isn't properly aligned. I remove UI customization in my code and get the same: http://take.ms/RE08R
Sorry for adding this here — I'm not sure it's worth a separate issue. @demerino

**Comment by demerino** [comment]
Got it. We'll look into this issue as well. Glad you're making use of the customization, looks good!

**Comment by demerino** [comment]
PR: https://github.com/braintree/braintree-ios-drop-in/pull/65

**Comment by demerino** [comment]
Should be fixed in 5.3.0
