### ISSUE TITLE
3d secure modal appears, entering verification password and then stays there.

### ISSUE THREAD

**Issue by dkalaitzidis** [braintree/braintree-ios-drop-in#68]
### General information

Using Braintree (4.9.6)
Using BraintreeDropIn (5.2.3)

* Environment: Sandbox & Production
* iOS Version and Device:  iOS 11 on an iPhone 7, iPhone X, Simulator
* Integration type and version: LATEST

Upadate:

After installed Braintree/3D-Secure i have the modal on request, i put the 1234 code, loads another page but it stays there and i don't have any control over it. Cancel not working.

Currently the App Store version uses older libraries and it works as expected, but the new builds when using a similar code like bellow, the 3d secure never appears.

```
func showDropIn(clientTokenOrTokenizationKey: String) {
    let request =  BTDropInRequest()
         request.threeDSecureVerification = true
         request.amount = "1.00"
    let dropIn = BTDropInController(authorization: clientTokenOrTokenizationKey, request: request)
    { (controller, result, error) in
        if (error != nil) {
            print("ERROR")
        } else if (result?.isCancelled == true) {
            print("CANCELLED")
        } else if let result = result {
            // Use the BTDropInResult properties to update your UI
            // result.paymentOptionType
            // result.paymentMethod
            // result.paymentIcon
            // result.paymentDescription
        }
        controller.dismiss(animated: true, completion: nil)
    }
    self.present(dropIn!, animated: true, completion: nil)
}
```
Is it an issue on latest version? 
Thank you.

**Comment by demerino** [comment]
Can you verify the exact versions of Drop-in and Braintree being used? Can you also confirm that your `client token` has 3D Secure enabled (you can base 64 decode it and look for `threeDSecureEnabled`).

My test using Braintree 4.9.6 and Drop-in 5.2.3 - iPhone X simulator - displayed the 3DS flow in `sandbox`.

**Comment by dkalaitzidis** [comment]
Directly from Pod Install:

Using Braintree (4.9.6)
Using BraintreeDropIn (5.2.3)

Now running on Sandbox mode, paypal works as expected. Displays the sandbox screen and adds the sandbox user.

Also, i've decoded the token and has threeDSecureEnabled:true

Also, copied & pasted the code from above (like the example) and still after entering the 4111-1111-1111-1111 card in sandbox mode 3d secure never appears. The drop in closes and the modal for the 3d secure never appears.

**Comment by dkalaitzidis** [comment]
I managed to pop the 3D secure page but only after i added on Podfile the 'Braintree/3D-Secure' but now after i'm entering the 1234 code is stays there... even cancel not working to close the modal.

**Comment by dkalaitzidis** [comment]
I have update the title and original post with my current status

**Comment by dkalaitzidis** [comment]
OK it seems to be a hierarchy issue with the app. I've fixed it, so i close the issue. There is no problem with the SDK.
