### ISSUE TITLE
Credit card formatter is broken after edit

### ISSUE THREAD

**Issue by megimix** [braintree/braintree-ios-drop-in#69]
### General information

* SDK/Library version:"braintree/braintree-ios-drop-in" "5.2.3"
* Environment: null
* iOS Version and Device: all
* Integration type and version: Carthage 0.26.2

Credit card forma is broken after editing card num, fist number in the last tuple. 

![credit card formatter error](https://user-images.githubusercontent.com/2083237/33524241-507a49cc-d821-11e7-845f-c4f4c6b90409.gif)

**Comment by demerino** [comment]
@megimix Based on your screenshot, this doesn't appear to be the basic Braintree Drop-in associated with this repo. Do you have any other information to share on how you are integrating and what the code for displaying Drop-in is? This will help us investigate the issue further.

**Comment by crookedneighbor** [comment]
@megimix Going to close this since we haven't heard back from you. Feel free to comment here if you need further assistance.
