### ISSUE TITLE
NSURL -999 Error when 3d secure is enabled for a certain card

### ISSUE THREAD

**Issue by dkalaitzidis** [braintree/braintree-ios-drop-in#70]
### General information

Using Braintree (4.9.6)
Using BraintreeDropIn (5.2.3)

Environment: Sandbox & Production
iOS Version and Device: iOS 11 on an iPhone 7, iPhone X, Simulator
Integration type and version: LATEST

### Issue description

Hello, after working with the SDK, we have an issue when we try to 3d-secure a certain card. With other cards is DropIn and 3d-secure works as expected.

The problem seems to be with this type of card (Sweden):

MasterCard Debit
Bank: SEB

The SDK tries for 3d-secure but returns the NSURL -999 error, then closes the modal.

**Comment by demerino** [comment]
@dkalaitzidis We're working on a solution for this issue and we'll update when it is available.

**Comment by demerino** [comment]
Update: The new 3DS _browser switch_ flow is now available. We're working on adding this to Drop-in.

**Comment by demerino** [comment]
`6.0.0` should properly support a SEB card. There is a small issue on SEB's side where the `BankID on this device` flow doesn't work and it is being addressed by SEB. Authorizing via SMS should work.
