### ISSUE TITLE
Localisation of existing payment description

### ISSUE THREAD

**Issue by mwoollard** [braintree/braintree-ios-drop-in#71]
### General information

* SDK/Library version: 5.2.3
* Environment: Sandbox
* iOS Version and Device: iOS 11.1 on an iPhone 7
* Integration type and version: Custom

### Issue description

We are getting the payment description string for existing payment in English and not localised to the device setting (`[BTDropInResult paymentDescription]`). So 'ending 1111' as opposed to 'ende 1111' when device set to German. Being seen in both iOS and Android use of the SDK. Is this due to still working against Sandbox or some other issue?

Thanks
Mark

**Comment by demerino** [comment]
That string is not translated in the SDKs. You might want to show the "last 2" instead.

**Comment by crookedneighbor** [comment]
To clarify, the payment description is coming from the API response from the Braintree Gateway and is not translated. You can use last 2 or last 4 params as David mentioned and provide your own text if desired.
