### ISSUE TITLE
Expiry Date Keyboard iPhone X Layout Issue

### ISSUE THREAD

**Issue by meismyles** [braintree/braintree-ios-drop-in#72]
### General information

* SDK/Library version:  5.3.0
* Environment:  Sandbox & Production
* iOS Version and Device:  11.1.2 - iPhone X
* Integration type and version:  CocoaPods

### Issue description

I see you fixed the majority of iPhone X issues raised in #62 but the expiry date custom keyboard for the drop-in UI doesn't seem to be constrained to the safe area.

See screenshot below:
![braintreekeyboardissue](https://user-images.githubusercontent.com/6603912/34042203-d7a6924c-e19b-11e7-866e-4925f06c5c66.png)

**Comment by demerino** [comment]
@meismyles Thanks for pointing this out, we'll work on this for an upcoming release.

**Comment by demerino** [comment]
`6.1.0` should fix this issue.
