### ISSUE TITLE
User need a way to specify if they want to Save the Credit Car for later use or not

### ISSUE THREAD

**Issue by Daxito** [braintree/braintree-ios-drop-in#78]
Hi,
I just started to use this drop-in and noticed two missing key features:
1. A way for the user to specify he wants to Save the credit card info for later use
2. A way to delete any previous Credit Card Info.

Please advice

**Comment by sdcoffey** [comment]
Hey @Daxito,

Thanks for the feedback. There is currently no way for the user to opt out of vaulting in Drop-in. The recommended workaround is to place something in your UI, before presenting Drop-in, where the user can determine whether they want the payment method they are about to enter to be saved. Depending on what they say, you can then initialize Drop-in with a Client Token if they'd like to vault, or a Tokenization Key if they dont. Check out our [docs on authorization](https://developers.braintreepayments.com/guides/authorization/overview#capabilities) for more info about the various privileges associated with each.

Likewise, there is also no way for users to delete payment methods in the Drop-in UI. However, you can [delete them server side if you wish](https://developers.braintreepayments.com/guides/payment-methods/ruby#delete). 

See [this issue](https://github.com/braintree/braintree-ios-drop-in/issues/57) for more disucussion on the second point.

I'm going to close this issue. Please comment on the issue linked above to contribute to the discussion on deleting payment methods inside Drop-in.
