### ISSUE TITLE
apple pay

### ISSUE THREAD

**Issue by Kane-Sendgrid** [braintree/braintree-ios-drop-in#82]
Is apple pay integration working as intended? Why request.paymentMethod should be always nil?
I wonder if there are plans to implement full apple pay flow in drop in and return payment nonce like with other methods or that is impossible for some reasons?

As I understand right now all apply pay integration does it returns you "Customer wants to pay with Apple Pay" and nothing else, so we have to initiate flow manually?

**Comment by demerino** [comment]
Correct, you should show the ApplePay payment sheet yourself towards the end of your flow once the customer has selected ApplePay from Drop-in. This approach gives you full control of displaying the ApplePay UI.

We don't have plans to display the sheet within Drop-in.

**Comment by Kane-Sendgrid** [comment]
Thanks @demerino! What is the reason for not showing sheet inside drop-in?

**Comment by demerino** [comment]
@Kane-Sendgrid In the end this option was the most flexible for a wide variety of use cases - including many where showing ApplePay within Drop-in is not desired. It also continues to give merchants full control of the params for the ApplePay presentation.

Example One:
A merchant might have a confirmation screen that allows a customer to adjust shipping method (overnight, standard, etc...) _after_ Drop-in has been displayed and the payment method is chosen. In this case the merchant wants to show the ApplePay sheet with the final shipping cost once that confirmation button is clicked.

Example Two:
A merchant wants to show the ApplePay sheet as soon as they select ApplePay. They can detect the choice in the callback and present it after dismissing Drop-in.

From a user experience/design perspective, there was a bit of concern when displaying the Drop-in sheet with the ApplePay sheet on top of it.

These are just a handful of considerations we looked into when deciding how to handle ApplePay within Drop-in. We're open to feedback if this solution doesn't work for you.

**Comment by Kane-Sendgrid** [comment]
Got it, I'm closing this ticket.

**Comment by Kane-Sendgrid** [comment]
P.S. Still would be nice to have opt-in, simple flow, where it works just like any other method returning nonce. It's not very hard to implement manually, but I have gut feeling that this simple flow is what 99% of user will need.

**Comment by demerino** [comment]
👍 We appreciate the feedback and will take it into account.
