### ISSUE TITLE
Compile issue 

### ISSUE THREAD

**Issue by EjazAppxone** [braintree/braintree-ios-drop-in#83]
BraintreeDropIn (5.3.0)
Xcode 9.2
Swift 4
Cocoapods 1.1.1
![screen shot 2018-03-12 at 11 00 45 am](https://user-images.githubusercontent.com/37285517/37267968-3ee8a9d0-25e5-11e8-8bcb-94f50de26134.png)

Facing compiling issues with Swift 4 and Xcode 9. 
Easily fixable by Xcode suggestions. Please update soon if possible.. forking it for now... 

Thanks

**Comment by demerino** [comment]
@EjazAppxone This was fixed in `6.0.1`. The major version bump was for a 3D Secure update - and it was relatively small. I suggest updating to the latest version `6.1.0`.

**Comment by EjazAppxone** [comment]
Ok, sorry about that I didn't checked the releases... 
Updating my Pods repo to get the new release now... 
Thanks for quick reply...
