### ISSUE TITLE
CVV error is not displayed

### ISSUE THREAD

**Issue by Minishlink** [braintree/braintree-ios-drop-in#84]
### General information

* SDK/Library version: 6.1.0
* Environment: Sandbox
* iOS Version and Device: iOS 10.3.1 on an iPhone 6
* Integration type and version: CocoaPods 1.2.1

### Issue description

Use the following card:
* Number: 4000 0000 0000 0002
* CVV: 200

This raises an error `Record not found`, and nothing is displayed on the Braintree UI.

Note that on Android, an error is successfully displayed in the drop-in UI.

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll look into this

**Comment by demerino** [comment]
@Minishlink You are right that the behavior is different from Android and Web where the UI is updated rather than returning the error. We'll work on a fix for this to put it inline with the other SDKs.

**Comment by demerino** [comment]
This should be fixed in 6.2.0: https://github.com/braintree/braintree-ios-drop-in/releases/tag/6.2.0
