### ISSUE TITLE
Incorrect dismissal of BTDropInController

### ISSUE THREAD

**Issue by mwoollard** [braintree/braintree-ios-drop-in#86]
### General information

* SDK/Library version: 6.1.0 (but seen in earlier too)
* Environment: Sandbox (but would apply to production)
* iOS Version and Device: Applies to all iPhone
* Integration type and version: Custom

### Issue description

In handling errors returned from `BTDropInController` (for example enter a real card number when in sandbox mode) we are wanting to display `UIAlertController` with the error message *without* dismissing the `BTDropInController` so the user can immediately try and enter a different card. 

What we are seeing is when the `UIAlertController` is dismissed the `BTDropInController` panel is animated off screen but it has not actually been dismissed. You end up with screen with translucent overlay but no BT UI to interact with and the user is stuck with no option except to forcibly terminate the app.

Looking at the code the issue is with putting the dismiss animation that removes the `BTDropInController` UI in an overridden version of `dismissViewControllerAnimated:completion:`. This method may be called to dismiss a presented (child) controller not just the instance itself and thus the animation shouldn't really be here (or this method overridden). `UIAlertController` calls the presenting view controller's `dismissViewControllerAnimated:completion:` method and thus when presented over a `BTDropInController` instance this issue is seen.

I would suggest that a custom presentation be built for the UI animation that is being implemented here (see [UIViewControllerTransitioningDelegate](https://developer.apple.com/documentation/uikit/uiviewcontrollertransitioningdelegate)) and thus leave the OS to decide when to animate the controller on and off screen. Additional benefit is you could easily then implement interactive dismissal and support swipe down gesture to remove as additional feature if desired.

Alternatively just check if `[self presentedViewController]` non-nil in your current implementation of `dismissViewControllerAnimated:completion` and if so just call through to the superclass implementation.

Before dismissal
![simulator screen shot - iphone x - 2018-03-13 at 09 09 40](https://user-images.githubusercontent.com/150681/37332345-53e1954a-269e-11e8-8ab2-ab8f06b11221.png)

After dismissal - you cannot now interact with the apps UI
![simulator screen shot - iphone x - 2018-03-13 at 09 09 47](https://user-images.githubusercontent.com/150681/37332350-572f96c0-269e-11e8-9b69-bd70d476a236.png)

**Comment by demerino** [comment]
@mwoollard We will look into the underlying issue here. We created a [PR](https://github.com/braintree/braintree-ios-drop-in/pull/85) yesterday to display an error to the user when invalid card information is entered - rather than returning an error.

**Comment by mwoollard** [comment]
Thanks for quick response 👍

**Comment by demerino** [comment]
This should be fixed in 6.2.0: https://github.com/braintree/braintree-ios-drop-in/releases/tag/6.2.0
