### ISSUE TITLE
Build with carthage issues

### ISSUE THREAD

**Issue by e-tip** [braintree/braintree-ios-drop-in#90]
### General information

* SDK/Library version: 6.1.0
* Environment: Sandbox
* iOS Version and Device: iOS 11.2.6 on iPhone 8
* Integration type and version: Carthage 0.29.0

### Issue description
While trying to add Braintree support to my app i get some errors.
The first difference between the documentation and my case is that i had to add one more framework which is not listed in the minimum frameworks list stated [here](https://developers.braintreepayments.com/start/hello-client/ios/v4) which is BraintreePaymentFlow.framework
The second issue i've found is that when importing Braintree using import Braintree i get 
`"No such module "Braintree"`

**Comment by demerino** [comment]
@e-tip Thanks for the feedback. `BraintreePaymentFlow` is a new requirement and we'll update those docs.

For the second issue, what does your import statement look like and what version of Swift are you using?

**Comment by e-tip** [comment]
Hi @demerino ,
My import looks like 
`import BraintreeDropIn
import Braintree`
and i'm using swift version 4.
Removing import Braintree i can successfully use the sdk

**Comment by demerino** [comment]
@e-tip Thanks for the info. I'm glad it works!

> Note that Carthage only supports dynamic frameworks

https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

I believe you'll import using the `framework` definition you specified in your `Cartfile`.  Maybe you can try `import BraintreeCore` or any other module that you'll need. Let us know if that works.

Example:
```
import BraintreeApplePay
import BraintreeCard
import BraintreeCore
import BraintreeDataCollector
import BraintreePayPal
```

**Comment by e-tip** [comment]
@demerino yes everything works using the name i can see in the framework. The only issue i was facing was about documentation that in my case tells to import Braintree which is not available. Thanks for your support

**Comment by demerino** [comment]
Our code snippets lean towards a `cocoapods` style integration. We've refrained from adding more complexity to the docs which currently cover `objc` and `swift`. We'll see if we can come up with an appropriate solution.

We appreciate the feedback. I'm going to close this issue.
