### ISSUE TITLE
Postcode only allows numeric input

### ISSUE THREAD

**Issue by phawk** [braintree/braintree-ios-drop-in#94]
### General information

* SDK/Library version: 4.14.0
* Environment: Both
* iOS Version and Device: iOS 11, iPhone 8
* Integration type and version: Cocoapods 1.4.0

### Issue description

When using the drop-in UI on a UK based environment the Post code field displays, but it provides an example that looks rather like a zip code, it also provides only a numeric input keypad and doesn't allow me to enter a valid postcode, therefore I cannot process payments.

<img width="188" alt="screen shot 2018-04-23 at 15 26 48" src="https://user-images.githubusercontent.com/456019/39133026-236f379a-470b-11e8-8d35-fc001e93ea55.png">

**Comment by bluk** [comment]
Hello, can you try setting the [`[BTUIKAppearance sharedInstance].postalCodeFormFieldKeyboardType`](https://github.com/braintree/braintree-ios-drop-in/blob/master/BraintreeUIKit/Public/BTUIKAppearance.h#L47) property to an appropriate keyboard and seeing if that works for you?

**Comment by phawk** [comment]
@bluk thanks for getting back so quickly! 

Yes I was able to get postcode keyboard with:

```swift
BTUIKAppearance.sharedInstance().postalCodeFormFieldKeyboardType = .alphabet
```

The placeholder is still not the best showing `12345` when it should be something like `N11 3AB`, but at least it will allow us to take payments 🙂

**Comment by jackellenberger** [comment]
I'm going to go ahead and close this issue unless something else goes awry, @phawk. We'll add a task to our todo list to update the helper text based on locale, thanks for bringing that to our attention!
