### ISSUE TITLE
Select Payment UI Problem.

### ISSUE THREAD

**Issue by WillsChau** [braintree/braintree-ios-drop-in#95]
### General information

* SDK/Library version: latest version
* Environment:  Sandbox 
* iOS Version and Device: any iOS
* Integration type and version: 

### Issue description

Select Payment UI Problem.

<img width="342" alt="screen shot 2018-04-25 at 12 43 48 am" src="https://user-images.githubusercontent.com/38696360/39195118-76b41e8a-4822-11e8-9ec3-51724441e5af.png">

**Comment by bluk** [comment]
Hello, can you give the version that is in your `Podfile.lock` for `BraintreeDropIn`? This should have been fixed in `6.1.0`. You may have to change your `Podfile` to allow you to use the latest version and then run `pod update`. Also, you may have to run `pod repo update` to get the latest specs.

**Comment by crookedneighbor** [comment]
@WillsChau I'm going to close this do to inactivity, but feel free to comment here if you need additional assistance.
