### ISSUE TITLE
yld: Library not loaded: @rpath/BraintreePaymentFlow.framework/BraintreePaymentFlow Reason: image not found

### ISSUE THREAD

**Issue by engrsandeep** [braintree/braintree-ios-drop-in#97]
Hi,

Can you please help me to solve out below issue .

I am using xcode 9.3

dyld: Library not loaded: @rpath/BraintreePaymentFlow.framework/BraintreePaymentFlow
  Referenced from: /Users/sandeepmittal/Library/Developer/CoreSimulator/Devices/E49A62AD-4F5D-45A7-A4E8-35D0D0267A39/data/Containers/Bundle/Application/E460B926-B0BC-42DC-93BA-0833F1EBED89/Mobilinnov.app/Frameworks/BraintreeDropIn.framework/BraintreeDropIn
  Reason: image not found
(lldb)

**Comment by demerino** [comment]
Drop-in 6.X now requires the new `BraintreePaymentFlow` module: https://github.com/braintree/braintree-ios-drop-in/blob/master/CHANGELOG.md#600-2018-02-07

It should be included automatically if you're integrating via Cocoapods, otherwise you'll need to import it appropriately for your integration style.

Let us know if you're still having issues.

**Comment by engrsandeep** [comment]
I have added below frameworks. I did not found any framework for BraintreePaymentFlow? Can you please guide.

![image](https://user-images.githubusercontent.com/10007250/39674929-2b067cd2-5171-11e8-8217-18ebb0f6f75b.png)
![image](https://user-images.githubusercontent.com/10007250/39674931-30d2f4ba-5171-11e8-9579-73617c4f693f.png)

**Comment by engrsandeep** [comment]
@demerino Can you please help to solve out this issue. Can you send me some guidelines how to create .framework of modules.  I will try to do that.

**Comment by demerino** [comment]
You can follow the same process you used for the other modules - make sure you have pulled the latest version of Braintree (not this Drop-in repo) as well. We'll be able to help more if you can let us know how you are integrating? Manually or via Carthage? 

Here is the directory for the PaymentFlow module: https://github.com/braintree/braintree_ios/tree/master/BraintreePaymentFlow

**Comment by engrsandeep** [comment]
@demerino Actually, i am not an iOS Developer. 
I use this plugin https://github.com/Taracque/cordova-plugin-braintree
This plugin provide .framework of all modules. if you can guide or point doc, i can create that as well.

**Comment by engrsandeep** [comment]
Thank you @demerino It working fine now...

**Comment by tarun-agathsya** [comment]
@engrsandeep I am still facing this issue when i try to run my ionic app. 
can u please help me resolve this?

**Comment by engrsandeep** [comment]
@tarun-agathsya  how you are integrating braintree with ionic. If you are using braintree plugin for ionic, then you need to rebuild frameworks

**Comment by tarun-agathsya** [comment]
HI @engrsandeep, yes I am using Braintree plugin, can you please guide me on what has to be done.

**Comment by tarun-agathsya** [comment]
@engrsandeep can you please guide me on rebuilding the frameworks

**Comment by kheber92** [comment]
I'm also facing the same issue when trying to run an Ionic project with Braintree in xCode:

> dyld: Library not loaded: @rpath/BraintreeVenmo.framework/BraintreeVenmo
>   Referenced from: /Users/me/Library/Developer/CoreSimulator/Devices/F9A78FB0-E0E5-4789-B294-F76B82A0F995/data/Containers/Bundle/Application/4648048B-A4D5-44FF-84F1-9B07B7574F4F/MyAppPayment.app/MyAppPayment
>   Reason: image not found
> (lldb) 

Does anybody know how to fix that?
cordova-plugin-braintree 0.5.1
