### ISSUE TITLE
3dsecure under test and drop-in

### ISSUE THREAD

**Issue by WEMAPP** [braintree/braintree-ios-drop-in#99]
I'm trying to implement a drop-in payment with 3dsecure.
I followed the steps by installing pod 'Braintree / 3D-Secure' and
BTDropInRequest * request = [[BTDropInRequest alloc] init];
request.threeDSecureVerification = true
request.amount = "1.00"

But the payment is successful without opening the 3d secure page.
What am I doing wrong?
I'm using the sdk version 4.15

**Comment by crookedneighbor** [comment]
Are you using one of the test cards listed in the [Download the Cardinal Consumer Authentication Test Cases Guide v1.18.0 (PDF)](https://developers.braintreepayments.com/files/Centinel.IntegrationGuide.ConsumerAuthentication_TestCases_v1_18_0_20160823.pdf) link [from the 3D Secure docs?](https://developers.braintreepayments.com/guides/3d-secure/testing-go-live/ruby#testing)

**Comment by crookedneighbor** [comment]
@WEMAPP Gonna close this due to inactivity. Comment here if you still need assistance.
